
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ActionParticipant` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ActionParticipant
 * *
 *  * ======================================================
 *  * ACTION PARTICIPANT (LIGAÇÃO)
 *  * ======================================================
 */
export type ActionParticipantModel = runtime.Types.Result.DefaultSelection<Prisma.$ActionParticipantPayload>

export type AggregateActionParticipant = {
  _count: ActionParticipantCountAggregateOutputType | null
  _min: ActionParticipantMinAggregateOutputType | null
  _max: ActionParticipantMaxAggregateOutputType | null
}

export type ActionParticipantMinAggregateOutputType = {
  id: string | null
  actionId: string | null
  participantId: string | null
}

export type ActionParticipantMaxAggregateOutputType = {
  id: string | null
  actionId: string | null
  participantId: string | null
}

export type ActionParticipantCountAggregateOutputType = {
  id: number
  actionId: number
  participantId: number
  _all: number
}


export type ActionParticipantMinAggregateInputType = {
  id?: true
  actionId?: true
  participantId?: true
}

export type ActionParticipantMaxAggregateInputType = {
  id?: true
  actionId?: true
  participantId?: true
}

export type ActionParticipantCountAggregateInputType = {
  id?: true
  actionId?: true
  participantId?: true
  _all?: true
}

export type ActionParticipantAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ActionParticipant to aggregate.
   */
  where?: Prisma.ActionParticipantWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActionParticipants to fetch.
   */
  orderBy?: Prisma.ActionParticipantOrderByWithRelationInput | Prisma.ActionParticipantOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ActionParticipantWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActionParticipants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActionParticipants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ActionParticipants
  **/
  _count?: true | ActionParticipantCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ActionParticipantMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ActionParticipantMaxAggregateInputType
}

export type GetActionParticipantAggregateType<T extends ActionParticipantAggregateArgs> = {
      [P in keyof T & keyof AggregateActionParticipant]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateActionParticipant[P]>
    : Prisma.GetScalarType<T[P], AggregateActionParticipant[P]>
}




export type ActionParticipantGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ActionParticipantWhereInput
  orderBy?: Prisma.ActionParticipantOrderByWithAggregationInput | Prisma.ActionParticipantOrderByWithAggregationInput[]
  by: Prisma.ActionParticipantScalarFieldEnum[] | Prisma.ActionParticipantScalarFieldEnum
  having?: Prisma.ActionParticipantScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ActionParticipantCountAggregateInputType | true
  _min?: ActionParticipantMinAggregateInputType
  _max?: ActionParticipantMaxAggregateInputType
}

export type ActionParticipantGroupByOutputType = {
  id: string
  actionId: string
  participantId: string
  _count: ActionParticipantCountAggregateOutputType | null
  _min: ActionParticipantMinAggregateOutputType | null
  _max: ActionParticipantMaxAggregateOutputType | null
}

type GetActionParticipantGroupByPayload<T extends ActionParticipantGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ActionParticipantGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ActionParticipantGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ActionParticipantGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ActionParticipantGroupByOutputType[P]>
      }
    >
  >



export type ActionParticipantWhereInput = {
  AND?: Prisma.ActionParticipantWhereInput | Prisma.ActionParticipantWhereInput[]
  OR?: Prisma.ActionParticipantWhereInput[]
  NOT?: Prisma.ActionParticipantWhereInput | Prisma.ActionParticipantWhereInput[]
  id?: Prisma.StringFilter<"ActionParticipant"> | string
  actionId?: Prisma.StringFilter<"ActionParticipant"> | string
  participantId?: Prisma.StringFilter<"ActionParticipant"> | string
  action?: Prisma.XOR<Prisma.ActionScalarRelationFilter, Prisma.ActionWhereInput>
  participant?: Prisma.XOR<Prisma.ParticipantScalarRelationFilter, Prisma.ParticipantWhereInput>
}

export type ActionParticipantOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  actionId?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
  action?: Prisma.ActionOrderByWithRelationInput
  participant?: Prisma.ParticipantOrderByWithRelationInput
}

export type ActionParticipantWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ActionParticipantWhereInput | Prisma.ActionParticipantWhereInput[]
  OR?: Prisma.ActionParticipantWhereInput[]
  NOT?: Prisma.ActionParticipantWhereInput | Prisma.ActionParticipantWhereInput[]
  actionId?: Prisma.StringFilter<"ActionParticipant"> | string
  participantId?: Prisma.StringFilter<"ActionParticipant"> | string
  action?: Prisma.XOR<Prisma.ActionScalarRelationFilter, Prisma.ActionWhereInput>
  participant?: Prisma.XOR<Prisma.ParticipantScalarRelationFilter, Prisma.ParticipantWhereInput>
}, "id">

export type ActionParticipantOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  actionId?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
  _count?: Prisma.ActionParticipantCountOrderByAggregateInput
  _max?: Prisma.ActionParticipantMaxOrderByAggregateInput
  _min?: Prisma.ActionParticipantMinOrderByAggregateInput
}

export type ActionParticipantScalarWhereWithAggregatesInput = {
  AND?: Prisma.ActionParticipantScalarWhereWithAggregatesInput | Prisma.ActionParticipantScalarWhereWithAggregatesInput[]
  OR?: Prisma.ActionParticipantScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ActionParticipantScalarWhereWithAggregatesInput | Prisma.ActionParticipantScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ActionParticipant"> | string
  actionId?: Prisma.StringWithAggregatesFilter<"ActionParticipant"> | string
  participantId?: Prisma.StringWithAggregatesFilter<"ActionParticipant"> | string
}

export type ActionParticipantCreateInput = {
  id?: string
  action: Prisma.ActionCreateNestedOneWithoutParticipantsInput
  participant: Prisma.ParticipantCreateNestedOneWithoutActionsInput
}

export type ActionParticipantUncheckedCreateInput = {
  id?: string
  actionId: string
  participantId: string
}

export type ActionParticipantUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.ActionUpdateOneRequiredWithoutParticipantsNestedInput
  participant?: Prisma.ParticipantUpdateOneRequiredWithoutActionsNestedInput
}

export type ActionParticipantUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  actionId?: Prisma.StringFieldUpdateOperationsInput | string
  participantId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ActionParticipantCreateManyInput = {
  id?: string
  actionId: string
  participantId: string
}

export type ActionParticipantUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ActionParticipantUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  actionId?: Prisma.StringFieldUpdateOperationsInput | string
  participantId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ActionParticipantListRelationFilter = {
  every?: Prisma.ActionParticipantWhereInput
  some?: Prisma.ActionParticipantWhereInput
  none?: Prisma.ActionParticipantWhereInput
}

export type ActionParticipantOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ActionParticipantCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  actionId?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
}

export type ActionParticipantMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  actionId?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
}

export type ActionParticipantMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  actionId?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
}

export type ActionParticipantCreateNestedManyWithoutActionInput = {
  create?: Prisma.XOR<Prisma.ActionParticipantCreateWithoutActionInput, Prisma.ActionParticipantUncheckedCreateWithoutActionInput> | Prisma.ActionParticipantCreateWithoutActionInput[] | Prisma.ActionParticipantUncheckedCreateWithoutActionInput[]
  connectOrCreate?: Prisma.ActionParticipantCreateOrConnectWithoutActionInput | Prisma.ActionParticipantCreateOrConnectWithoutActionInput[]
  createMany?: Prisma.ActionParticipantCreateManyActionInputEnvelope
  connect?: Prisma.ActionParticipantWhereUniqueInput | Prisma.ActionParticipantWhereUniqueInput[]
}

export type ActionParticipantUncheckedCreateNestedManyWithoutActionInput = {
  create?: Prisma.XOR<Prisma.ActionParticipantCreateWithoutActionInput, Prisma.ActionParticipantUncheckedCreateWithoutActionInput> | Prisma.ActionParticipantCreateWithoutActionInput[] | Prisma.ActionParticipantUncheckedCreateWithoutActionInput[]
  connectOrCreate?: Prisma.ActionParticipantCreateOrConnectWithoutActionInput | Prisma.ActionParticipantCreateOrConnectWithoutActionInput[]
  createMany?: Prisma.ActionParticipantCreateManyActionInputEnvelope
  connect?: Prisma.ActionParticipantWhereUniqueInput | Prisma.ActionParticipantWhereUniqueInput[]
}

export type ActionParticipantUpdateManyWithoutActionNestedInput = {
  create?: Prisma.XOR<Prisma.ActionParticipantCreateWithoutActionInput, Prisma.ActionParticipantUncheckedCreateWithoutActionInput> | Prisma.ActionParticipantCreateWithoutActionInput[] | Prisma.ActionParticipantUncheckedCreateWithoutActionInput[]
  connectOrCreate?: Prisma.ActionParticipantCreateOrConnectWithoutActionInput | Prisma.ActionParticipantCreateOrConnectWithoutActionInput[]
  upsert?: Prisma.ActionParticipantUpsertWithWhereUniqueWithoutActionInput | Prisma.ActionParticipantUpsertWithWhereUniqueWithoutActionInput[]
  createMany?: Prisma.ActionParticipantCreateManyActionInputEnvelope
  set?: Prisma.ActionParticipantWhereUniqueInput | Prisma.ActionParticipantWhereUniqueInput[]
  disconnect?: Prisma.ActionParticipantWhereUniqueInput | Prisma.ActionParticipantWhereUniqueInput[]
  delete?: Prisma.ActionParticipantWhereUniqueInput | Prisma.ActionParticipantWhereUniqueInput[]
  connect?: Prisma.ActionParticipantWhereUniqueInput | Prisma.ActionParticipantWhereUniqueInput[]
  update?: Prisma.ActionParticipantUpdateWithWhereUniqueWithoutActionInput | Prisma.ActionParticipantUpdateWithWhereUniqueWithoutActionInput[]
  updateMany?: Prisma.ActionParticipantUpdateManyWithWhereWithoutActionInput | Prisma.ActionParticipantUpdateManyWithWhereWithoutActionInput[]
  deleteMany?: Prisma.ActionParticipantScalarWhereInput | Prisma.ActionParticipantScalarWhereInput[]
}

export type ActionParticipantUncheckedUpdateManyWithoutActionNestedInput = {
  create?: Prisma.XOR<Prisma.ActionParticipantCreateWithoutActionInput, Prisma.ActionParticipantUncheckedCreateWithoutActionInput> | Prisma.ActionParticipantCreateWithoutActionInput[] | Prisma.ActionParticipantUncheckedCreateWithoutActionInput[]
  connectOrCreate?: Prisma.ActionParticipantCreateOrConnectWithoutActionInput | Prisma.ActionParticipantCreateOrConnectWithoutActionInput[]
  upsert?: Prisma.ActionParticipantUpsertWithWhereUniqueWithoutActionInput | Prisma.ActionParticipantUpsertWithWhereUniqueWithoutActionInput[]
  createMany?: Prisma.ActionParticipantCreateManyActionInputEnvelope
  set?: Prisma.ActionParticipantWhereUniqueInput | Prisma.ActionParticipantWhereUniqueInput[]
  disconnect?: Prisma.ActionParticipantWhereUniqueInput | Prisma.ActionParticipantWhereUniqueInput[]
  delete?: Prisma.ActionParticipantWhereUniqueInput | Prisma.ActionParticipantWhereUniqueInput[]
  connect?: Prisma.ActionParticipantWhereUniqueInput | Prisma.ActionParticipantWhereUniqueInput[]
  update?: Prisma.ActionParticipantUpdateWithWhereUniqueWithoutActionInput | Prisma.ActionParticipantUpdateWithWhereUniqueWithoutActionInput[]
  updateMany?: Prisma.ActionParticipantUpdateManyWithWhereWithoutActionInput | Prisma.ActionParticipantUpdateManyWithWhereWithoutActionInput[]
  deleteMany?: Prisma.ActionParticipantScalarWhereInput | Prisma.ActionParticipantScalarWhereInput[]
}

export type ActionParticipantCreateNestedManyWithoutParticipantInput = {
  create?: Prisma.XOR<Prisma.ActionParticipantCreateWithoutParticipantInput, Prisma.ActionParticipantUncheckedCreateWithoutParticipantInput> | Prisma.ActionParticipantCreateWithoutParticipantInput[] | Prisma.ActionParticipantUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.ActionParticipantCreateOrConnectWithoutParticipantInput | Prisma.ActionParticipantCreateOrConnectWithoutParticipantInput[]
  createMany?: Prisma.ActionParticipantCreateManyParticipantInputEnvelope
  connect?: Prisma.ActionParticipantWhereUniqueInput | Prisma.ActionParticipantWhereUniqueInput[]
}

export type ActionParticipantUncheckedCreateNestedManyWithoutParticipantInput = {
  create?: Prisma.XOR<Prisma.ActionParticipantCreateWithoutParticipantInput, Prisma.ActionParticipantUncheckedCreateWithoutParticipantInput> | Prisma.ActionParticipantCreateWithoutParticipantInput[] | Prisma.ActionParticipantUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.ActionParticipantCreateOrConnectWithoutParticipantInput | Prisma.ActionParticipantCreateOrConnectWithoutParticipantInput[]
  createMany?: Prisma.ActionParticipantCreateManyParticipantInputEnvelope
  connect?: Prisma.ActionParticipantWhereUniqueInput | Prisma.ActionParticipantWhereUniqueInput[]
}

export type ActionParticipantUpdateManyWithoutParticipantNestedInput = {
  create?: Prisma.XOR<Prisma.ActionParticipantCreateWithoutParticipantInput, Prisma.ActionParticipantUncheckedCreateWithoutParticipantInput> | Prisma.ActionParticipantCreateWithoutParticipantInput[] | Prisma.ActionParticipantUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.ActionParticipantCreateOrConnectWithoutParticipantInput | Prisma.ActionParticipantCreateOrConnectWithoutParticipantInput[]
  upsert?: Prisma.ActionParticipantUpsertWithWhereUniqueWithoutParticipantInput | Prisma.ActionParticipantUpsertWithWhereUniqueWithoutParticipantInput[]
  createMany?: Prisma.ActionParticipantCreateManyParticipantInputEnvelope
  set?: Prisma.ActionParticipantWhereUniqueInput | Prisma.ActionParticipantWhereUniqueInput[]
  disconnect?: Prisma.ActionParticipantWhereUniqueInput | Prisma.ActionParticipantWhereUniqueInput[]
  delete?: Prisma.ActionParticipantWhereUniqueInput | Prisma.ActionParticipantWhereUniqueInput[]
  connect?: Prisma.ActionParticipantWhereUniqueInput | Prisma.ActionParticipantWhereUniqueInput[]
  update?: Prisma.ActionParticipantUpdateWithWhereUniqueWithoutParticipantInput | Prisma.ActionParticipantUpdateWithWhereUniqueWithoutParticipantInput[]
  updateMany?: Prisma.ActionParticipantUpdateManyWithWhereWithoutParticipantInput | Prisma.ActionParticipantUpdateManyWithWhereWithoutParticipantInput[]
  deleteMany?: Prisma.ActionParticipantScalarWhereInput | Prisma.ActionParticipantScalarWhereInput[]
}

export type ActionParticipantUncheckedUpdateManyWithoutParticipantNestedInput = {
  create?: Prisma.XOR<Prisma.ActionParticipantCreateWithoutParticipantInput, Prisma.ActionParticipantUncheckedCreateWithoutParticipantInput> | Prisma.ActionParticipantCreateWithoutParticipantInput[] | Prisma.ActionParticipantUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.ActionParticipantCreateOrConnectWithoutParticipantInput | Prisma.ActionParticipantCreateOrConnectWithoutParticipantInput[]
  upsert?: Prisma.ActionParticipantUpsertWithWhereUniqueWithoutParticipantInput | Prisma.ActionParticipantUpsertWithWhereUniqueWithoutParticipantInput[]
  createMany?: Prisma.ActionParticipantCreateManyParticipantInputEnvelope
  set?: Prisma.ActionParticipantWhereUniqueInput | Prisma.ActionParticipantWhereUniqueInput[]
  disconnect?: Prisma.ActionParticipantWhereUniqueInput | Prisma.ActionParticipantWhereUniqueInput[]
  delete?: Prisma.ActionParticipantWhereUniqueInput | Prisma.ActionParticipantWhereUniqueInput[]
  connect?: Prisma.ActionParticipantWhereUniqueInput | Prisma.ActionParticipantWhereUniqueInput[]
  update?: Prisma.ActionParticipantUpdateWithWhereUniqueWithoutParticipantInput | Prisma.ActionParticipantUpdateWithWhereUniqueWithoutParticipantInput[]
  updateMany?: Prisma.ActionParticipantUpdateManyWithWhereWithoutParticipantInput | Prisma.ActionParticipantUpdateManyWithWhereWithoutParticipantInput[]
  deleteMany?: Prisma.ActionParticipantScalarWhereInput | Prisma.ActionParticipantScalarWhereInput[]
}

export type ActionParticipantCreateWithoutActionInput = {
  id?: string
  participant: Prisma.ParticipantCreateNestedOneWithoutActionsInput
}

export type ActionParticipantUncheckedCreateWithoutActionInput = {
  id?: string
  participantId: string
}

export type ActionParticipantCreateOrConnectWithoutActionInput = {
  where: Prisma.ActionParticipantWhereUniqueInput
  create: Prisma.XOR<Prisma.ActionParticipantCreateWithoutActionInput, Prisma.ActionParticipantUncheckedCreateWithoutActionInput>
}

export type ActionParticipantCreateManyActionInputEnvelope = {
  data: Prisma.ActionParticipantCreateManyActionInput | Prisma.ActionParticipantCreateManyActionInput[]
  skipDuplicates?: boolean
}

export type ActionParticipantUpsertWithWhereUniqueWithoutActionInput = {
  where: Prisma.ActionParticipantWhereUniqueInput
  update: Prisma.XOR<Prisma.ActionParticipantUpdateWithoutActionInput, Prisma.ActionParticipantUncheckedUpdateWithoutActionInput>
  create: Prisma.XOR<Prisma.ActionParticipantCreateWithoutActionInput, Prisma.ActionParticipantUncheckedCreateWithoutActionInput>
}

export type ActionParticipantUpdateWithWhereUniqueWithoutActionInput = {
  where: Prisma.ActionParticipantWhereUniqueInput
  data: Prisma.XOR<Prisma.ActionParticipantUpdateWithoutActionInput, Prisma.ActionParticipantUncheckedUpdateWithoutActionInput>
}

export type ActionParticipantUpdateManyWithWhereWithoutActionInput = {
  where: Prisma.ActionParticipantScalarWhereInput
  data: Prisma.XOR<Prisma.ActionParticipantUpdateManyMutationInput, Prisma.ActionParticipantUncheckedUpdateManyWithoutActionInput>
}

export type ActionParticipantScalarWhereInput = {
  AND?: Prisma.ActionParticipantScalarWhereInput | Prisma.ActionParticipantScalarWhereInput[]
  OR?: Prisma.ActionParticipantScalarWhereInput[]
  NOT?: Prisma.ActionParticipantScalarWhereInput | Prisma.ActionParticipantScalarWhereInput[]
  id?: Prisma.StringFilter<"ActionParticipant"> | string
  actionId?: Prisma.StringFilter<"ActionParticipant"> | string
  participantId?: Prisma.StringFilter<"ActionParticipant"> | string
}

export type ActionParticipantCreateWithoutParticipantInput = {
  id?: string
  action: Prisma.ActionCreateNestedOneWithoutParticipantsInput
}

export type ActionParticipantUncheckedCreateWithoutParticipantInput = {
  id?: string
  actionId: string
}

export type ActionParticipantCreateOrConnectWithoutParticipantInput = {
  where: Prisma.ActionParticipantWhereUniqueInput
  create: Prisma.XOR<Prisma.ActionParticipantCreateWithoutParticipantInput, Prisma.ActionParticipantUncheckedCreateWithoutParticipantInput>
}

export type ActionParticipantCreateManyParticipantInputEnvelope = {
  data: Prisma.ActionParticipantCreateManyParticipantInput | Prisma.ActionParticipantCreateManyParticipantInput[]
  skipDuplicates?: boolean
}

export type ActionParticipantUpsertWithWhereUniqueWithoutParticipantInput = {
  where: Prisma.ActionParticipantWhereUniqueInput
  update: Prisma.XOR<Prisma.ActionParticipantUpdateWithoutParticipantInput, Prisma.ActionParticipantUncheckedUpdateWithoutParticipantInput>
  create: Prisma.XOR<Prisma.ActionParticipantCreateWithoutParticipantInput, Prisma.ActionParticipantUncheckedCreateWithoutParticipantInput>
}

export type ActionParticipantUpdateWithWhereUniqueWithoutParticipantInput = {
  where: Prisma.ActionParticipantWhereUniqueInput
  data: Prisma.XOR<Prisma.ActionParticipantUpdateWithoutParticipantInput, Prisma.ActionParticipantUncheckedUpdateWithoutParticipantInput>
}

export type ActionParticipantUpdateManyWithWhereWithoutParticipantInput = {
  where: Prisma.ActionParticipantScalarWhereInput
  data: Prisma.XOR<Prisma.ActionParticipantUpdateManyMutationInput, Prisma.ActionParticipantUncheckedUpdateManyWithoutParticipantInput>
}

export type ActionParticipantCreateManyActionInput = {
  id?: string
  participantId: string
}

export type ActionParticipantUpdateWithoutActionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  participant?: Prisma.ParticipantUpdateOneRequiredWithoutActionsNestedInput
}

export type ActionParticipantUncheckedUpdateWithoutActionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  participantId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ActionParticipantUncheckedUpdateManyWithoutActionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  participantId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ActionParticipantCreateManyParticipantInput = {
  id?: string
  actionId: string
}

export type ActionParticipantUpdateWithoutParticipantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.ActionUpdateOneRequiredWithoutParticipantsNestedInput
}

export type ActionParticipantUncheckedUpdateWithoutParticipantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  actionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ActionParticipantUncheckedUpdateManyWithoutParticipantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  actionId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type ActionParticipantSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  actionId?: boolean
  participantId?: boolean
  action?: boolean | Prisma.ActionDefaultArgs<ExtArgs>
  participant?: boolean | Prisma.ParticipantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["actionParticipant"]>

export type ActionParticipantSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  actionId?: boolean
  participantId?: boolean
  action?: boolean | Prisma.ActionDefaultArgs<ExtArgs>
  participant?: boolean | Prisma.ParticipantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["actionParticipant"]>

export type ActionParticipantSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  actionId?: boolean
  participantId?: boolean
  action?: boolean | Prisma.ActionDefaultArgs<ExtArgs>
  participant?: boolean | Prisma.ParticipantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["actionParticipant"]>

export type ActionParticipantSelectScalar = {
  id?: boolean
  actionId?: boolean
  participantId?: boolean
}

export type ActionParticipantOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "actionId" | "participantId", ExtArgs["result"]["actionParticipant"]>
export type ActionParticipantInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  action?: boolean | Prisma.ActionDefaultArgs<ExtArgs>
  participant?: boolean | Prisma.ParticipantDefaultArgs<ExtArgs>
}
export type ActionParticipantIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  action?: boolean | Prisma.ActionDefaultArgs<ExtArgs>
  participant?: boolean | Prisma.ParticipantDefaultArgs<ExtArgs>
}
export type ActionParticipantIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  action?: boolean | Prisma.ActionDefaultArgs<ExtArgs>
  participant?: boolean | Prisma.ParticipantDefaultArgs<ExtArgs>
}

export type $ActionParticipantPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ActionParticipant"
  objects: {
    action: Prisma.$ActionPayload<ExtArgs>
    participant: Prisma.$ParticipantPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    actionId: string
    participantId: string
  }, ExtArgs["result"]["actionParticipant"]>
  composites: {}
}

export type ActionParticipantGetPayload<S extends boolean | null | undefined | ActionParticipantDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ActionParticipantPayload, S>

export type ActionParticipantCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ActionParticipantFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ActionParticipantCountAggregateInputType | true
  }

export interface ActionParticipantDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ActionParticipant'], meta: { name: 'ActionParticipant' } }
  /**
   * Find zero or one ActionParticipant that matches the filter.
   * @param {ActionParticipantFindUniqueArgs} args - Arguments to find a ActionParticipant
   * @example
   * // Get one ActionParticipant
   * const actionParticipant = await prisma.actionParticipant.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ActionParticipantFindUniqueArgs>(args: Prisma.SelectSubset<T, ActionParticipantFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ActionParticipantClient<runtime.Types.Result.GetResult<Prisma.$ActionParticipantPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ActionParticipant that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ActionParticipantFindUniqueOrThrowArgs} args - Arguments to find a ActionParticipant
   * @example
   * // Get one ActionParticipant
   * const actionParticipant = await prisma.actionParticipant.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ActionParticipantFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ActionParticipantFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ActionParticipantClient<runtime.Types.Result.GetResult<Prisma.$ActionParticipantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ActionParticipant that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionParticipantFindFirstArgs} args - Arguments to find a ActionParticipant
   * @example
   * // Get one ActionParticipant
   * const actionParticipant = await prisma.actionParticipant.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ActionParticipantFindFirstArgs>(args?: Prisma.SelectSubset<T, ActionParticipantFindFirstArgs<ExtArgs>>): Prisma.Prisma__ActionParticipantClient<runtime.Types.Result.GetResult<Prisma.$ActionParticipantPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ActionParticipant that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionParticipantFindFirstOrThrowArgs} args - Arguments to find a ActionParticipant
   * @example
   * // Get one ActionParticipant
   * const actionParticipant = await prisma.actionParticipant.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ActionParticipantFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ActionParticipantFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ActionParticipantClient<runtime.Types.Result.GetResult<Prisma.$ActionParticipantPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ActionParticipants that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionParticipantFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ActionParticipants
   * const actionParticipants = await prisma.actionParticipant.findMany()
   * 
   * // Get first 10 ActionParticipants
   * const actionParticipants = await prisma.actionParticipant.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const actionParticipantWithIdOnly = await prisma.actionParticipant.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ActionParticipantFindManyArgs>(args?: Prisma.SelectSubset<T, ActionParticipantFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActionParticipantPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ActionParticipant.
   * @param {ActionParticipantCreateArgs} args - Arguments to create a ActionParticipant.
   * @example
   * // Create one ActionParticipant
   * const ActionParticipant = await prisma.actionParticipant.create({
   *   data: {
   *     // ... data to create a ActionParticipant
   *   }
   * })
   * 
   */
  create<T extends ActionParticipantCreateArgs>(args: Prisma.SelectSubset<T, ActionParticipantCreateArgs<ExtArgs>>): Prisma.Prisma__ActionParticipantClient<runtime.Types.Result.GetResult<Prisma.$ActionParticipantPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ActionParticipants.
   * @param {ActionParticipantCreateManyArgs} args - Arguments to create many ActionParticipants.
   * @example
   * // Create many ActionParticipants
   * const actionParticipant = await prisma.actionParticipant.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ActionParticipantCreateManyArgs>(args?: Prisma.SelectSubset<T, ActionParticipantCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ActionParticipants and returns the data saved in the database.
   * @param {ActionParticipantCreateManyAndReturnArgs} args - Arguments to create many ActionParticipants.
   * @example
   * // Create many ActionParticipants
   * const actionParticipant = await prisma.actionParticipant.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ActionParticipants and only return the `id`
   * const actionParticipantWithIdOnly = await prisma.actionParticipant.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ActionParticipantCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ActionParticipantCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActionParticipantPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ActionParticipant.
   * @param {ActionParticipantDeleteArgs} args - Arguments to delete one ActionParticipant.
   * @example
   * // Delete one ActionParticipant
   * const ActionParticipant = await prisma.actionParticipant.delete({
   *   where: {
   *     // ... filter to delete one ActionParticipant
   *   }
   * })
   * 
   */
  delete<T extends ActionParticipantDeleteArgs>(args: Prisma.SelectSubset<T, ActionParticipantDeleteArgs<ExtArgs>>): Prisma.Prisma__ActionParticipantClient<runtime.Types.Result.GetResult<Prisma.$ActionParticipantPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ActionParticipant.
   * @param {ActionParticipantUpdateArgs} args - Arguments to update one ActionParticipant.
   * @example
   * // Update one ActionParticipant
   * const actionParticipant = await prisma.actionParticipant.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ActionParticipantUpdateArgs>(args: Prisma.SelectSubset<T, ActionParticipantUpdateArgs<ExtArgs>>): Prisma.Prisma__ActionParticipantClient<runtime.Types.Result.GetResult<Prisma.$ActionParticipantPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ActionParticipants.
   * @param {ActionParticipantDeleteManyArgs} args - Arguments to filter ActionParticipants to delete.
   * @example
   * // Delete a few ActionParticipants
   * const { count } = await prisma.actionParticipant.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ActionParticipantDeleteManyArgs>(args?: Prisma.SelectSubset<T, ActionParticipantDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ActionParticipants.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionParticipantUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ActionParticipants
   * const actionParticipant = await prisma.actionParticipant.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ActionParticipantUpdateManyArgs>(args: Prisma.SelectSubset<T, ActionParticipantUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ActionParticipants and returns the data updated in the database.
   * @param {ActionParticipantUpdateManyAndReturnArgs} args - Arguments to update many ActionParticipants.
   * @example
   * // Update many ActionParticipants
   * const actionParticipant = await prisma.actionParticipant.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ActionParticipants and only return the `id`
   * const actionParticipantWithIdOnly = await prisma.actionParticipant.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ActionParticipantUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ActionParticipantUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActionParticipantPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ActionParticipant.
   * @param {ActionParticipantUpsertArgs} args - Arguments to update or create a ActionParticipant.
   * @example
   * // Update or create a ActionParticipant
   * const actionParticipant = await prisma.actionParticipant.upsert({
   *   create: {
   *     // ... data to create a ActionParticipant
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ActionParticipant we want to update
   *   }
   * })
   */
  upsert<T extends ActionParticipantUpsertArgs>(args: Prisma.SelectSubset<T, ActionParticipantUpsertArgs<ExtArgs>>): Prisma.Prisma__ActionParticipantClient<runtime.Types.Result.GetResult<Prisma.$ActionParticipantPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ActionParticipants.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionParticipantCountArgs} args - Arguments to filter ActionParticipants to count.
   * @example
   * // Count the number of ActionParticipants
   * const count = await prisma.actionParticipant.count({
   *   where: {
   *     // ... the filter for the ActionParticipants we want to count
   *   }
   * })
  **/
  count<T extends ActionParticipantCountArgs>(
    args?: Prisma.Subset<T, ActionParticipantCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ActionParticipantCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ActionParticipant.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionParticipantAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ActionParticipantAggregateArgs>(args: Prisma.Subset<T, ActionParticipantAggregateArgs>): Prisma.PrismaPromise<GetActionParticipantAggregateType<T>>

  /**
   * Group by ActionParticipant.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionParticipantGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ActionParticipantGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ActionParticipantGroupByArgs['orderBy'] }
      : { orderBy?: ActionParticipantGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ActionParticipantGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetActionParticipantGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ActionParticipant model
 */
readonly fields: ActionParticipantFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ActionParticipant.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ActionParticipantClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  action<T extends Prisma.ActionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ActionDefaultArgs<ExtArgs>>): Prisma.Prisma__ActionClient<runtime.Types.Result.GetResult<Prisma.$ActionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  participant<T extends Prisma.ParticipantDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ParticipantDefaultArgs<ExtArgs>>): Prisma.Prisma__ParticipantClient<runtime.Types.Result.GetResult<Prisma.$ParticipantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ActionParticipant model
 */
export interface ActionParticipantFieldRefs {
  readonly id: Prisma.FieldRef<"ActionParticipant", 'String'>
  readonly actionId: Prisma.FieldRef<"ActionParticipant", 'String'>
  readonly participantId: Prisma.FieldRef<"ActionParticipant", 'String'>
}
    

// Custom InputTypes
/**
 * ActionParticipant findUnique
 */
export type ActionParticipantFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionParticipant
   */
  select?: Prisma.ActionParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionParticipant
   */
  omit?: Prisma.ActionParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionParticipantInclude<ExtArgs> | null
  /**
   * Filter, which ActionParticipant to fetch.
   */
  where: Prisma.ActionParticipantWhereUniqueInput
}

/**
 * ActionParticipant findUniqueOrThrow
 */
export type ActionParticipantFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionParticipant
   */
  select?: Prisma.ActionParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionParticipant
   */
  omit?: Prisma.ActionParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionParticipantInclude<ExtArgs> | null
  /**
   * Filter, which ActionParticipant to fetch.
   */
  where: Prisma.ActionParticipantWhereUniqueInput
}

/**
 * ActionParticipant findFirst
 */
export type ActionParticipantFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionParticipant
   */
  select?: Prisma.ActionParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionParticipant
   */
  omit?: Prisma.ActionParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionParticipantInclude<ExtArgs> | null
  /**
   * Filter, which ActionParticipant to fetch.
   */
  where?: Prisma.ActionParticipantWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActionParticipants to fetch.
   */
  orderBy?: Prisma.ActionParticipantOrderByWithRelationInput | Prisma.ActionParticipantOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ActionParticipants.
   */
  cursor?: Prisma.ActionParticipantWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActionParticipants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActionParticipants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ActionParticipants.
   */
  distinct?: Prisma.ActionParticipantScalarFieldEnum | Prisma.ActionParticipantScalarFieldEnum[]
}

/**
 * ActionParticipant findFirstOrThrow
 */
export type ActionParticipantFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionParticipant
   */
  select?: Prisma.ActionParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionParticipant
   */
  omit?: Prisma.ActionParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionParticipantInclude<ExtArgs> | null
  /**
   * Filter, which ActionParticipant to fetch.
   */
  where?: Prisma.ActionParticipantWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActionParticipants to fetch.
   */
  orderBy?: Prisma.ActionParticipantOrderByWithRelationInput | Prisma.ActionParticipantOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ActionParticipants.
   */
  cursor?: Prisma.ActionParticipantWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActionParticipants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActionParticipants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ActionParticipants.
   */
  distinct?: Prisma.ActionParticipantScalarFieldEnum | Prisma.ActionParticipantScalarFieldEnum[]
}

/**
 * ActionParticipant findMany
 */
export type ActionParticipantFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionParticipant
   */
  select?: Prisma.ActionParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionParticipant
   */
  omit?: Prisma.ActionParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionParticipantInclude<ExtArgs> | null
  /**
   * Filter, which ActionParticipants to fetch.
   */
  where?: Prisma.ActionParticipantWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActionParticipants to fetch.
   */
  orderBy?: Prisma.ActionParticipantOrderByWithRelationInput | Prisma.ActionParticipantOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ActionParticipants.
   */
  cursor?: Prisma.ActionParticipantWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActionParticipants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActionParticipants.
   */
  skip?: number
  distinct?: Prisma.ActionParticipantScalarFieldEnum | Prisma.ActionParticipantScalarFieldEnum[]
}

/**
 * ActionParticipant create
 */
export type ActionParticipantCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionParticipant
   */
  select?: Prisma.ActionParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionParticipant
   */
  omit?: Prisma.ActionParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionParticipantInclude<ExtArgs> | null
  /**
   * The data needed to create a ActionParticipant.
   */
  data: Prisma.XOR<Prisma.ActionParticipantCreateInput, Prisma.ActionParticipantUncheckedCreateInput>
}

/**
 * ActionParticipant createMany
 */
export type ActionParticipantCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ActionParticipants.
   */
  data: Prisma.ActionParticipantCreateManyInput | Prisma.ActionParticipantCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ActionParticipant createManyAndReturn
 */
export type ActionParticipantCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionParticipant
   */
  select?: Prisma.ActionParticipantSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ActionParticipant
   */
  omit?: Prisma.ActionParticipantOmit<ExtArgs> | null
  /**
   * The data used to create many ActionParticipants.
   */
  data: Prisma.ActionParticipantCreateManyInput | Prisma.ActionParticipantCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionParticipantIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ActionParticipant update
 */
export type ActionParticipantUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionParticipant
   */
  select?: Prisma.ActionParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionParticipant
   */
  omit?: Prisma.ActionParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionParticipantInclude<ExtArgs> | null
  /**
   * The data needed to update a ActionParticipant.
   */
  data: Prisma.XOR<Prisma.ActionParticipantUpdateInput, Prisma.ActionParticipantUncheckedUpdateInput>
  /**
   * Choose, which ActionParticipant to update.
   */
  where: Prisma.ActionParticipantWhereUniqueInput
}

/**
 * ActionParticipant updateMany
 */
export type ActionParticipantUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ActionParticipants.
   */
  data: Prisma.XOR<Prisma.ActionParticipantUpdateManyMutationInput, Prisma.ActionParticipantUncheckedUpdateManyInput>
  /**
   * Filter which ActionParticipants to update
   */
  where?: Prisma.ActionParticipantWhereInput
  /**
   * Limit how many ActionParticipants to update.
   */
  limit?: number
}

/**
 * ActionParticipant updateManyAndReturn
 */
export type ActionParticipantUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionParticipant
   */
  select?: Prisma.ActionParticipantSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ActionParticipant
   */
  omit?: Prisma.ActionParticipantOmit<ExtArgs> | null
  /**
   * The data used to update ActionParticipants.
   */
  data: Prisma.XOR<Prisma.ActionParticipantUpdateManyMutationInput, Prisma.ActionParticipantUncheckedUpdateManyInput>
  /**
   * Filter which ActionParticipants to update
   */
  where?: Prisma.ActionParticipantWhereInput
  /**
   * Limit how many ActionParticipants to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionParticipantIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ActionParticipant upsert
 */
export type ActionParticipantUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionParticipant
   */
  select?: Prisma.ActionParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionParticipant
   */
  omit?: Prisma.ActionParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionParticipantInclude<ExtArgs> | null
  /**
   * The filter to search for the ActionParticipant to update in case it exists.
   */
  where: Prisma.ActionParticipantWhereUniqueInput
  /**
   * In case the ActionParticipant found by the `where` argument doesn't exist, create a new ActionParticipant with this data.
   */
  create: Prisma.XOR<Prisma.ActionParticipantCreateInput, Prisma.ActionParticipantUncheckedCreateInput>
  /**
   * In case the ActionParticipant was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ActionParticipantUpdateInput, Prisma.ActionParticipantUncheckedUpdateInput>
}

/**
 * ActionParticipant delete
 */
export type ActionParticipantDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionParticipant
   */
  select?: Prisma.ActionParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionParticipant
   */
  omit?: Prisma.ActionParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionParticipantInclude<ExtArgs> | null
  /**
   * Filter which ActionParticipant to delete.
   */
  where: Prisma.ActionParticipantWhereUniqueInput
}

/**
 * ActionParticipant deleteMany
 */
export type ActionParticipantDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ActionParticipants to delete
   */
  where?: Prisma.ActionParticipantWhereInput
  /**
   * Limit how many ActionParticipants to delete.
   */
  limit?: number
}

/**
 * ActionParticipant without action
 */
export type ActionParticipantDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionParticipant
   */
  select?: Prisma.ActionParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionParticipant
   */
  omit?: Prisma.ActionParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionParticipantInclude<ExtArgs> | null
}
