
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ActionConfig` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ActionConfig
 * *
 *  * ======================================================
 *  * ACTION CONFIG (TIPOS DE AÇÃO)
 *  * ======================================================
 */
export type ActionConfigModel = runtime.Types.Result.DefaultSelection<Prisma.$ActionConfigPayload>

export type AggregateActionConfig = {
  _count: ActionConfigCountAggregateOutputType | null
  _avg: ActionConfigAvgAggregateOutputType | null
  _sum: ActionConfigSumAggregateOutputType | null
  _min: ActionConfigMinAggregateOutputType | null
  _max: ActionConfigMaxAggregateOutputType | null
}

export type ActionConfigAvgAggregateOutputType = {
  id: number | null
}

export type ActionConfigSumAggregateOutputType = {
  id: number | null
}

export type ActionConfigMinAggregateOutputType = {
  id: number | null
  name: string | null
  description: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ActionConfigMaxAggregateOutputType = {
  id: number | null
  name: string | null
  description: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ActionConfigCountAggregateOutputType = {
  id: number
  name: number
  description: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ActionConfigAvgAggregateInputType = {
  id?: true
}

export type ActionConfigSumAggregateInputType = {
  id?: true
}

export type ActionConfigMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type ActionConfigMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type ActionConfigCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ActionConfigAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ActionConfig to aggregate.
   */
  where?: Prisma.ActionConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActionConfigs to fetch.
   */
  orderBy?: Prisma.ActionConfigOrderByWithRelationInput | Prisma.ActionConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ActionConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActionConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActionConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ActionConfigs
  **/
  _count?: true | ActionConfigCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ActionConfigAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ActionConfigSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ActionConfigMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ActionConfigMaxAggregateInputType
}

export type GetActionConfigAggregateType<T extends ActionConfigAggregateArgs> = {
      [P in keyof T & keyof AggregateActionConfig]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateActionConfig[P]>
    : Prisma.GetScalarType<T[P], AggregateActionConfig[P]>
}




export type ActionConfigGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ActionConfigWhereInput
  orderBy?: Prisma.ActionConfigOrderByWithAggregationInput | Prisma.ActionConfigOrderByWithAggregationInput[]
  by: Prisma.ActionConfigScalarFieldEnum[] | Prisma.ActionConfigScalarFieldEnum
  having?: Prisma.ActionConfigScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ActionConfigCountAggregateInputType | true
  _avg?: ActionConfigAvgAggregateInputType
  _sum?: ActionConfigSumAggregateInputType
  _min?: ActionConfigMinAggregateInputType
  _max?: ActionConfigMaxAggregateInputType
}

export type ActionConfigGroupByOutputType = {
  id: number
  name: string
  description: string | null
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  _count: ActionConfigCountAggregateOutputType | null
  _avg: ActionConfigAvgAggregateOutputType | null
  _sum: ActionConfigSumAggregateOutputType | null
  _min: ActionConfigMinAggregateOutputType | null
  _max: ActionConfigMaxAggregateOutputType | null
}

type GetActionConfigGroupByPayload<T extends ActionConfigGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ActionConfigGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ActionConfigGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ActionConfigGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ActionConfigGroupByOutputType[P]>
      }
    >
  >



export type ActionConfigWhereInput = {
  AND?: Prisma.ActionConfigWhereInput | Prisma.ActionConfigWhereInput[]
  OR?: Prisma.ActionConfigWhereInput[]
  NOT?: Prisma.ActionConfigWhereInput | Prisma.ActionConfigWhereInput[]
  id?: Prisma.IntFilter<"ActionConfig"> | number
  name?: Prisma.StringFilter<"ActionConfig"> | string
  description?: Prisma.StringNullableFilter<"ActionConfig"> | string | null
  isActive?: Prisma.BoolFilter<"ActionConfig"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ActionConfig"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ActionConfig"> | Date | string
  actions?: Prisma.ActionListRelationFilter
  actionDrafts?: Prisma.ActionDraftListRelationFilter
}

export type ActionConfigOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  actions?: Prisma.ActionOrderByRelationAggregateInput
  actionDrafts?: Prisma.ActionDraftOrderByRelationAggregateInput
}

export type ActionConfigWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ActionConfigWhereInput | Prisma.ActionConfigWhereInput[]
  OR?: Prisma.ActionConfigWhereInput[]
  NOT?: Prisma.ActionConfigWhereInput | Prisma.ActionConfigWhereInput[]
  name?: Prisma.StringFilter<"ActionConfig"> | string
  description?: Prisma.StringNullableFilter<"ActionConfig"> | string | null
  isActive?: Prisma.BoolFilter<"ActionConfig"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ActionConfig"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ActionConfig"> | Date | string
  actions?: Prisma.ActionListRelationFilter
  actionDrafts?: Prisma.ActionDraftListRelationFilter
}, "id">

export type ActionConfigOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ActionConfigCountOrderByAggregateInput
  _avg?: Prisma.ActionConfigAvgOrderByAggregateInput
  _max?: Prisma.ActionConfigMaxOrderByAggregateInput
  _min?: Prisma.ActionConfigMinOrderByAggregateInput
  _sum?: Prisma.ActionConfigSumOrderByAggregateInput
}

export type ActionConfigScalarWhereWithAggregatesInput = {
  AND?: Prisma.ActionConfigScalarWhereWithAggregatesInput | Prisma.ActionConfigScalarWhereWithAggregatesInput[]
  OR?: Prisma.ActionConfigScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ActionConfigScalarWhereWithAggregatesInput | Prisma.ActionConfigScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ActionConfig"> | number
  name?: Prisma.StringWithAggregatesFilter<"ActionConfig"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"ActionConfig"> | string | null
  isActive?: Prisma.BoolWithAggregatesFilter<"ActionConfig"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ActionConfig"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ActionConfig"> | Date | string
}

export type ActionConfigCreateInput = {
  name: string
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  actions?: Prisma.ActionCreateNestedManyWithoutActionConfigInput
  actionDrafts?: Prisma.ActionDraftCreateNestedManyWithoutActionConfigInput
}

export type ActionConfigUncheckedCreateInput = {
  id?: number
  name: string
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  actions?: Prisma.ActionUncheckedCreateNestedManyWithoutActionConfigInput
  actionDrafts?: Prisma.ActionDraftUncheckedCreateNestedManyWithoutActionConfigInput
}

export type ActionConfigUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actions?: Prisma.ActionUpdateManyWithoutActionConfigNestedInput
  actionDrafts?: Prisma.ActionDraftUpdateManyWithoutActionConfigNestedInput
}

export type ActionConfigUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actions?: Prisma.ActionUncheckedUpdateManyWithoutActionConfigNestedInput
  actionDrafts?: Prisma.ActionDraftUncheckedUpdateManyWithoutActionConfigNestedInput
}

export type ActionConfigCreateManyInput = {
  id?: number
  name: string
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ActionConfigUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActionConfigUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActionConfigCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ActionConfigAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type ActionConfigMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ActionConfigMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ActionConfigSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type ActionConfigScalarRelationFilter = {
  is?: Prisma.ActionConfigWhereInput
  isNot?: Prisma.ActionConfigWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type ActionConfigCreateNestedOneWithoutActionsInput = {
  create?: Prisma.XOR<Prisma.ActionConfigCreateWithoutActionsInput, Prisma.ActionConfigUncheckedCreateWithoutActionsInput>
  connectOrCreate?: Prisma.ActionConfigCreateOrConnectWithoutActionsInput
  connect?: Prisma.ActionConfigWhereUniqueInput
}

export type ActionConfigUpdateOneRequiredWithoutActionsNestedInput = {
  create?: Prisma.XOR<Prisma.ActionConfigCreateWithoutActionsInput, Prisma.ActionConfigUncheckedCreateWithoutActionsInput>
  connectOrCreate?: Prisma.ActionConfigCreateOrConnectWithoutActionsInput
  upsert?: Prisma.ActionConfigUpsertWithoutActionsInput
  connect?: Prisma.ActionConfigWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ActionConfigUpdateToOneWithWhereWithoutActionsInput, Prisma.ActionConfigUpdateWithoutActionsInput>, Prisma.ActionConfigUncheckedUpdateWithoutActionsInput>
}

export type ActionConfigCreateNestedOneWithoutActionDraftsInput = {
  create?: Prisma.XOR<Prisma.ActionConfigCreateWithoutActionDraftsInput, Prisma.ActionConfigUncheckedCreateWithoutActionDraftsInput>
  connectOrCreate?: Prisma.ActionConfigCreateOrConnectWithoutActionDraftsInput
  connect?: Prisma.ActionConfigWhereUniqueInput
}

export type ActionConfigUpdateOneRequiredWithoutActionDraftsNestedInput = {
  create?: Prisma.XOR<Prisma.ActionConfigCreateWithoutActionDraftsInput, Prisma.ActionConfigUncheckedCreateWithoutActionDraftsInput>
  connectOrCreate?: Prisma.ActionConfigCreateOrConnectWithoutActionDraftsInput
  upsert?: Prisma.ActionConfigUpsertWithoutActionDraftsInput
  connect?: Prisma.ActionConfigWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ActionConfigUpdateToOneWithWhereWithoutActionDraftsInput, Prisma.ActionConfigUpdateWithoutActionDraftsInput>, Prisma.ActionConfigUncheckedUpdateWithoutActionDraftsInput>
}

export type ActionConfigCreateWithoutActionsInput = {
  name: string
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  actionDrafts?: Prisma.ActionDraftCreateNestedManyWithoutActionConfigInput
}

export type ActionConfigUncheckedCreateWithoutActionsInput = {
  id?: number
  name: string
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  actionDrafts?: Prisma.ActionDraftUncheckedCreateNestedManyWithoutActionConfigInput
}

export type ActionConfigCreateOrConnectWithoutActionsInput = {
  where: Prisma.ActionConfigWhereUniqueInput
  create: Prisma.XOR<Prisma.ActionConfigCreateWithoutActionsInput, Prisma.ActionConfigUncheckedCreateWithoutActionsInput>
}

export type ActionConfigUpsertWithoutActionsInput = {
  update: Prisma.XOR<Prisma.ActionConfigUpdateWithoutActionsInput, Prisma.ActionConfigUncheckedUpdateWithoutActionsInput>
  create: Prisma.XOR<Prisma.ActionConfigCreateWithoutActionsInput, Prisma.ActionConfigUncheckedCreateWithoutActionsInput>
  where?: Prisma.ActionConfigWhereInput
}

export type ActionConfigUpdateToOneWithWhereWithoutActionsInput = {
  where?: Prisma.ActionConfigWhereInput
  data: Prisma.XOR<Prisma.ActionConfigUpdateWithoutActionsInput, Prisma.ActionConfigUncheckedUpdateWithoutActionsInput>
}

export type ActionConfigUpdateWithoutActionsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actionDrafts?: Prisma.ActionDraftUpdateManyWithoutActionConfigNestedInput
}

export type ActionConfigUncheckedUpdateWithoutActionsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actionDrafts?: Prisma.ActionDraftUncheckedUpdateManyWithoutActionConfigNestedInput
}

export type ActionConfigCreateWithoutActionDraftsInput = {
  name: string
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  actions?: Prisma.ActionCreateNestedManyWithoutActionConfigInput
}

export type ActionConfigUncheckedCreateWithoutActionDraftsInput = {
  id?: number
  name: string
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  actions?: Prisma.ActionUncheckedCreateNestedManyWithoutActionConfigInput
}

export type ActionConfigCreateOrConnectWithoutActionDraftsInput = {
  where: Prisma.ActionConfigWhereUniqueInput
  create: Prisma.XOR<Prisma.ActionConfigCreateWithoutActionDraftsInput, Prisma.ActionConfigUncheckedCreateWithoutActionDraftsInput>
}

export type ActionConfigUpsertWithoutActionDraftsInput = {
  update: Prisma.XOR<Prisma.ActionConfigUpdateWithoutActionDraftsInput, Prisma.ActionConfigUncheckedUpdateWithoutActionDraftsInput>
  create: Prisma.XOR<Prisma.ActionConfigCreateWithoutActionDraftsInput, Prisma.ActionConfigUncheckedCreateWithoutActionDraftsInput>
  where?: Prisma.ActionConfigWhereInput
}

export type ActionConfigUpdateToOneWithWhereWithoutActionDraftsInput = {
  where?: Prisma.ActionConfigWhereInput
  data: Prisma.XOR<Prisma.ActionConfigUpdateWithoutActionDraftsInput, Prisma.ActionConfigUncheckedUpdateWithoutActionDraftsInput>
}

export type ActionConfigUpdateWithoutActionDraftsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actions?: Prisma.ActionUpdateManyWithoutActionConfigNestedInput
}

export type ActionConfigUncheckedUpdateWithoutActionDraftsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actions?: Prisma.ActionUncheckedUpdateManyWithoutActionConfigNestedInput
}


/**
 * Count Type ActionConfigCountOutputType
 */

export type ActionConfigCountOutputType = {
  actions: number
  actionDrafts: number
}

export type ActionConfigCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  actions?: boolean | ActionConfigCountOutputTypeCountActionsArgs
  actionDrafts?: boolean | ActionConfigCountOutputTypeCountActionDraftsArgs
}

/**
 * ActionConfigCountOutputType without action
 */
export type ActionConfigCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionConfigCountOutputType
   */
  select?: Prisma.ActionConfigCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ActionConfigCountOutputType without action
 */
export type ActionConfigCountOutputTypeCountActionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ActionWhereInput
}

/**
 * ActionConfigCountOutputType without action
 */
export type ActionConfigCountOutputTypeCountActionDraftsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ActionDraftWhereInput
}


export type ActionConfigSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  actions?: boolean | Prisma.ActionConfig$actionsArgs<ExtArgs>
  actionDrafts?: boolean | Prisma.ActionConfig$actionDraftsArgs<ExtArgs>
  _count?: boolean | Prisma.ActionConfigCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["actionConfig"]>

export type ActionConfigSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["actionConfig"]>

export type ActionConfigSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["actionConfig"]>

export type ActionConfigSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ActionConfigOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["actionConfig"]>
export type ActionConfigInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  actions?: boolean | Prisma.ActionConfig$actionsArgs<ExtArgs>
  actionDrafts?: boolean | Prisma.ActionConfig$actionDraftsArgs<ExtArgs>
  _count?: boolean | Prisma.ActionConfigCountOutputTypeDefaultArgs<ExtArgs>
}
export type ActionConfigIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type ActionConfigIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ActionConfigPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ActionConfig"
  objects: {
    actions: Prisma.$ActionPayload<ExtArgs>[]
    actionDrafts: Prisma.$ActionDraftPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    description: string | null
    isActive: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["actionConfig"]>
  composites: {}
}

export type ActionConfigGetPayload<S extends boolean | null | undefined | ActionConfigDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ActionConfigPayload, S>

export type ActionConfigCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ActionConfigFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ActionConfigCountAggregateInputType | true
  }

export interface ActionConfigDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ActionConfig'], meta: { name: 'ActionConfig' } }
  /**
   * Find zero or one ActionConfig that matches the filter.
   * @param {ActionConfigFindUniqueArgs} args - Arguments to find a ActionConfig
   * @example
   * // Get one ActionConfig
   * const actionConfig = await prisma.actionConfig.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ActionConfigFindUniqueArgs>(args: Prisma.SelectSubset<T, ActionConfigFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ActionConfigClient<runtime.Types.Result.GetResult<Prisma.$ActionConfigPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ActionConfig that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ActionConfigFindUniqueOrThrowArgs} args - Arguments to find a ActionConfig
   * @example
   * // Get one ActionConfig
   * const actionConfig = await prisma.actionConfig.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ActionConfigFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ActionConfigFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ActionConfigClient<runtime.Types.Result.GetResult<Prisma.$ActionConfigPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ActionConfig that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionConfigFindFirstArgs} args - Arguments to find a ActionConfig
   * @example
   * // Get one ActionConfig
   * const actionConfig = await prisma.actionConfig.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ActionConfigFindFirstArgs>(args?: Prisma.SelectSubset<T, ActionConfigFindFirstArgs<ExtArgs>>): Prisma.Prisma__ActionConfigClient<runtime.Types.Result.GetResult<Prisma.$ActionConfigPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ActionConfig that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionConfigFindFirstOrThrowArgs} args - Arguments to find a ActionConfig
   * @example
   * // Get one ActionConfig
   * const actionConfig = await prisma.actionConfig.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ActionConfigFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ActionConfigFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ActionConfigClient<runtime.Types.Result.GetResult<Prisma.$ActionConfigPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ActionConfigs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionConfigFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ActionConfigs
   * const actionConfigs = await prisma.actionConfig.findMany()
   * 
   * // Get first 10 ActionConfigs
   * const actionConfigs = await prisma.actionConfig.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const actionConfigWithIdOnly = await prisma.actionConfig.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ActionConfigFindManyArgs>(args?: Prisma.SelectSubset<T, ActionConfigFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActionConfigPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ActionConfig.
   * @param {ActionConfigCreateArgs} args - Arguments to create a ActionConfig.
   * @example
   * // Create one ActionConfig
   * const ActionConfig = await prisma.actionConfig.create({
   *   data: {
   *     // ... data to create a ActionConfig
   *   }
   * })
   * 
   */
  create<T extends ActionConfigCreateArgs>(args: Prisma.SelectSubset<T, ActionConfigCreateArgs<ExtArgs>>): Prisma.Prisma__ActionConfigClient<runtime.Types.Result.GetResult<Prisma.$ActionConfigPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ActionConfigs.
   * @param {ActionConfigCreateManyArgs} args - Arguments to create many ActionConfigs.
   * @example
   * // Create many ActionConfigs
   * const actionConfig = await prisma.actionConfig.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ActionConfigCreateManyArgs>(args?: Prisma.SelectSubset<T, ActionConfigCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ActionConfigs and returns the data saved in the database.
   * @param {ActionConfigCreateManyAndReturnArgs} args - Arguments to create many ActionConfigs.
   * @example
   * // Create many ActionConfigs
   * const actionConfig = await prisma.actionConfig.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ActionConfigs and only return the `id`
   * const actionConfigWithIdOnly = await prisma.actionConfig.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ActionConfigCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ActionConfigCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActionConfigPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ActionConfig.
   * @param {ActionConfigDeleteArgs} args - Arguments to delete one ActionConfig.
   * @example
   * // Delete one ActionConfig
   * const ActionConfig = await prisma.actionConfig.delete({
   *   where: {
   *     // ... filter to delete one ActionConfig
   *   }
   * })
   * 
   */
  delete<T extends ActionConfigDeleteArgs>(args: Prisma.SelectSubset<T, ActionConfigDeleteArgs<ExtArgs>>): Prisma.Prisma__ActionConfigClient<runtime.Types.Result.GetResult<Prisma.$ActionConfigPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ActionConfig.
   * @param {ActionConfigUpdateArgs} args - Arguments to update one ActionConfig.
   * @example
   * // Update one ActionConfig
   * const actionConfig = await prisma.actionConfig.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ActionConfigUpdateArgs>(args: Prisma.SelectSubset<T, ActionConfigUpdateArgs<ExtArgs>>): Prisma.Prisma__ActionConfigClient<runtime.Types.Result.GetResult<Prisma.$ActionConfigPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ActionConfigs.
   * @param {ActionConfigDeleteManyArgs} args - Arguments to filter ActionConfigs to delete.
   * @example
   * // Delete a few ActionConfigs
   * const { count } = await prisma.actionConfig.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ActionConfigDeleteManyArgs>(args?: Prisma.SelectSubset<T, ActionConfigDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ActionConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionConfigUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ActionConfigs
   * const actionConfig = await prisma.actionConfig.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ActionConfigUpdateManyArgs>(args: Prisma.SelectSubset<T, ActionConfigUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ActionConfigs and returns the data updated in the database.
   * @param {ActionConfigUpdateManyAndReturnArgs} args - Arguments to update many ActionConfigs.
   * @example
   * // Update many ActionConfigs
   * const actionConfig = await prisma.actionConfig.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ActionConfigs and only return the `id`
   * const actionConfigWithIdOnly = await prisma.actionConfig.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ActionConfigUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ActionConfigUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActionConfigPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ActionConfig.
   * @param {ActionConfigUpsertArgs} args - Arguments to update or create a ActionConfig.
   * @example
   * // Update or create a ActionConfig
   * const actionConfig = await prisma.actionConfig.upsert({
   *   create: {
   *     // ... data to create a ActionConfig
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ActionConfig we want to update
   *   }
   * })
   */
  upsert<T extends ActionConfigUpsertArgs>(args: Prisma.SelectSubset<T, ActionConfigUpsertArgs<ExtArgs>>): Prisma.Prisma__ActionConfigClient<runtime.Types.Result.GetResult<Prisma.$ActionConfigPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ActionConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionConfigCountArgs} args - Arguments to filter ActionConfigs to count.
   * @example
   * // Count the number of ActionConfigs
   * const count = await prisma.actionConfig.count({
   *   where: {
   *     // ... the filter for the ActionConfigs we want to count
   *   }
   * })
  **/
  count<T extends ActionConfigCountArgs>(
    args?: Prisma.Subset<T, ActionConfigCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ActionConfigCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ActionConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionConfigAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ActionConfigAggregateArgs>(args: Prisma.Subset<T, ActionConfigAggregateArgs>): Prisma.PrismaPromise<GetActionConfigAggregateType<T>>

  /**
   * Group by ActionConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionConfigGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ActionConfigGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ActionConfigGroupByArgs['orderBy'] }
      : { orderBy?: ActionConfigGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ActionConfigGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetActionConfigGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ActionConfig model
 */
readonly fields: ActionConfigFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ActionConfig.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ActionConfigClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  actions<T extends Prisma.ActionConfig$actionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ActionConfig$actionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  actionDrafts<T extends Prisma.ActionConfig$actionDraftsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ActionConfig$actionDraftsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActionDraftPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ActionConfig model
 */
export interface ActionConfigFieldRefs {
  readonly id: Prisma.FieldRef<"ActionConfig", 'Int'>
  readonly name: Prisma.FieldRef<"ActionConfig", 'String'>
  readonly description: Prisma.FieldRef<"ActionConfig", 'String'>
  readonly isActive: Prisma.FieldRef<"ActionConfig", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"ActionConfig", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ActionConfig", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ActionConfig findUnique
 */
export type ActionConfigFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionConfig
   */
  select?: Prisma.ActionConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionConfig
   */
  omit?: Prisma.ActionConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionConfigInclude<ExtArgs> | null
  /**
   * Filter, which ActionConfig to fetch.
   */
  where: Prisma.ActionConfigWhereUniqueInput
}

/**
 * ActionConfig findUniqueOrThrow
 */
export type ActionConfigFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionConfig
   */
  select?: Prisma.ActionConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionConfig
   */
  omit?: Prisma.ActionConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionConfigInclude<ExtArgs> | null
  /**
   * Filter, which ActionConfig to fetch.
   */
  where: Prisma.ActionConfigWhereUniqueInput
}

/**
 * ActionConfig findFirst
 */
export type ActionConfigFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionConfig
   */
  select?: Prisma.ActionConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionConfig
   */
  omit?: Prisma.ActionConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionConfigInclude<ExtArgs> | null
  /**
   * Filter, which ActionConfig to fetch.
   */
  where?: Prisma.ActionConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActionConfigs to fetch.
   */
  orderBy?: Prisma.ActionConfigOrderByWithRelationInput | Prisma.ActionConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ActionConfigs.
   */
  cursor?: Prisma.ActionConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActionConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActionConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ActionConfigs.
   */
  distinct?: Prisma.ActionConfigScalarFieldEnum | Prisma.ActionConfigScalarFieldEnum[]
}

/**
 * ActionConfig findFirstOrThrow
 */
export type ActionConfigFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionConfig
   */
  select?: Prisma.ActionConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionConfig
   */
  omit?: Prisma.ActionConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionConfigInclude<ExtArgs> | null
  /**
   * Filter, which ActionConfig to fetch.
   */
  where?: Prisma.ActionConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActionConfigs to fetch.
   */
  orderBy?: Prisma.ActionConfigOrderByWithRelationInput | Prisma.ActionConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ActionConfigs.
   */
  cursor?: Prisma.ActionConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActionConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActionConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ActionConfigs.
   */
  distinct?: Prisma.ActionConfigScalarFieldEnum | Prisma.ActionConfigScalarFieldEnum[]
}

/**
 * ActionConfig findMany
 */
export type ActionConfigFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionConfig
   */
  select?: Prisma.ActionConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionConfig
   */
  omit?: Prisma.ActionConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionConfigInclude<ExtArgs> | null
  /**
   * Filter, which ActionConfigs to fetch.
   */
  where?: Prisma.ActionConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActionConfigs to fetch.
   */
  orderBy?: Prisma.ActionConfigOrderByWithRelationInput | Prisma.ActionConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ActionConfigs.
   */
  cursor?: Prisma.ActionConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActionConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActionConfigs.
   */
  skip?: number
  distinct?: Prisma.ActionConfigScalarFieldEnum | Prisma.ActionConfigScalarFieldEnum[]
}

/**
 * ActionConfig create
 */
export type ActionConfigCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionConfig
   */
  select?: Prisma.ActionConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionConfig
   */
  omit?: Prisma.ActionConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionConfigInclude<ExtArgs> | null
  /**
   * The data needed to create a ActionConfig.
   */
  data: Prisma.XOR<Prisma.ActionConfigCreateInput, Prisma.ActionConfigUncheckedCreateInput>
}

/**
 * ActionConfig createMany
 */
export type ActionConfigCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ActionConfigs.
   */
  data: Prisma.ActionConfigCreateManyInput | Prisma.ActionConfigCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ActionConfig createManyAndReturn
 */
export type ActionConfigCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionConfig
   */
  select?: Prisma.ActionConfigSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ActionConfig
   */
  omit?: Prisma.ActionConfigOmit<ExtArgs> | null
  /**
   * The data used to create many ActionConfigs.
   */
  data: Prisma.ActionConfigCreateManyInput | Prisma.ActionConfigCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ActionConfig update
 */
export type ActionConfigUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionConfig
   */
  select?: Prisma.ActionConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionConfig
   */
  omit?: Prisma.ActionConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionConfigInclude<ExtArgs> | null
  /**
   * The data needed to update a ActionConfig.
   */
  data: Prisma.XOR<Prisma.ActionConfigUpdateInput, Prisma.ActionConfigUncheckedUpdateInput>
  /**
   * Choose, which ActionConfig to update.
   */
  where: Prisma.ActionConfigWhereUniqueInput
}

/**
 * ActionConfig updateMany
 */
export type ActionConfigUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ActionConfigs.
   */
  data: Prisma.XOR<Prisma.ActionConfigUpdateManyMutationInput, Prisma.ActionConfigUncheckedUpdateManyInput>
  /**
   * Filter which ActionConfigs to update
   */
  where?: Prisma.ActionConfigWhereInput
  /**
   * Limit how many ActionConfigs to update.
   */
  limit?: number
}

/**
 * ActionConfig updateManyAndReturn
 */
export type ActionConfigUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionConfig
   */
  select?: Prisma.ActionConfigSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ActionConfig
   */
  omit?: Prisma.ActionConfigOmit<ExtArgs> | null
  /**
   * The data used to update ActionConfigs.
   */
  data: Prisma.XOR<Prisma.ActionConfigUpdateManyMutationInput, Prisma.ActionConfigUncheckedUpdateManyInput>
  /**
   * Filter which ActionConfigs to update
   */
  where?: Prisma.ActionConfigWhereInput
  /**
   * Limit how many ActionConfigs to update.
   */
  limit?: number
}

/**
 * ActionConfig upsert
 */
export type ActionConfigUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionConfig
   */
  select?: Prisma.ActionConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionConfig
   */
  omit?: Prisma.ActionConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionConfigInclude<ExtArgs> | null
  /**
   * The filter to search for the ActionConfig to update in case it exists.
   */
  where: Prisma.ActionConfigWhereUniqueInput
  /**
   * In case the ActionConfig found by the `where` argument doesn't exist, create a new ActionConfig with this data.
   */
  create: Prisma.XOR<Prisma.ActionConfigCreateInput, Prisma.ActionConfigUncheckedCreateInput>
  /**
   * In case the ActionConfig was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ActionConfigUpdateInput, Prisma.ActionConfigUncheckedUpdateInput>
}

/**
 * ActionConfig delete
 */
export type ActionConfigDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionConfig
   */
  select?: Prisma.ActionConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionConfig
   */
  omit?: Prisma.ActionConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionConfigInclude<ExtArgs> | null
  /**
   * Filter which ActionConfig to delete.
   */
  where: Prisma.ActionConfigWhereUniqueInput
}

/**
 * ActionConfig deleteMany
 */
export type ActionConfigDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ActionConfigs to delete
   */
  where?: Prisma.ActionConfigWhereInput
  /**
   * Limit how many ActionConfigs to delete.
   */
  limit?: number
}

/**
 * ActionConfig.actions
 */
export type ActionConfig$actionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Action
   */
  select?: Prisma.ActionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Action
   */
  omit?: Prisma.ActionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionInclude<ExtArgs> | null
  where?: Prisma.ActionWhereInput
  orderBy?: Prisma.ActionOrderByWithRelationInput | Prisma.ActionOrderByWithRelationInput[]
  cursor?: Prisma.ActionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ActionScalarFieldEnum | Prisma.ActionScalarFieldEnum[]
}

/**
 * ActionConfig.actionDrafts
 */
export type ActionConfig$actionDraftsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionDraft
   */
  select?: Prisma.ActionDraftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionDraft
   */
  omit?: Prisma.ActionDraftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionDraftInclude<ExtArgs> | null
  where?: Prisma.ActionDraftWhereInput
  orderBy?: Prisma.ActionDraftOrderByWithRelationInput | Prisma.ActionDraftOrderByWithRelationInput[]
  cursor?: Prisma.ActionDraftWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ActionDraftScalarFieldEnum | Prisma.ActionDraftScalarFieldEnum[]
}

/**
 * ActionConfig without action
 */
export type ActionConfigDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionConfig
   */
  select?: Prisma.ActionConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionConfig
   */
  omit?: Prisma.ActionConfigOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionConfigInclude<ExtArgs> | null
}
