
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ActionDraft` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ActionDraft
 * 
 */
export type ActionDraftModel = runtime.Types.Result.DefaultSelection<Prisma.$ActionDraftPayload>

export type AggregateActionDraft = {
  _count: ActionDraftCountAggregateOutputType | null
  _avg: ActionDraftAvgAggregateOutputType | null
  _sum: ActionDraftSumAggregateOutputType | null
  _min: ActionDraftMinAggregateOutputType | null
  _max: ActionDraftMaxAggregateOutputType | null
}

export type ActionDraftAvgAggregateOutputType = {
  actionConfigId: number | null
}

export type ActionDraftSumAggregateOutputType = {
  actionConfigId: number | null
}

export type ActionDraftMinAggregateOutputType = {
  id: string | null
  userId: string | null
  guildId: string | null
  actionConfigId: number | null
  rawParticipants: string | null
  createdAt: Date | null
  updatedAt: Date | null
  expiresAt: Date | null
}

export type ActionDraftMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  guildId: string | null
  actionConfigId: number | null
  rawParticipants: string | null
  createdAt: Date | null
  updatedAt: Date | null
  expiresAt: Date | null
}

export type ActionDraftCountAggregateOutputType = {
  id: number
  userId: number
  guildId: number
  actionConfigId: number
  rawParticipants: number
  parsedNames: number
  missingNames: number
  createdAt: number
  updatedAt: number
  expiresAt: number
  _all: number
}


export type ActionDraftAvgAggregateInputType = {
  actionConfigId?: true
}

export type ActionDraftSumAggregateInputType = {
  actionConfigId?: true
}

export type ActionDraftMinAggregateInputType = {
  id?: true
  userId?: true
  guildId?: true
  actionConfigId?: true
  rawParticipants?: true
  createdAt?: true
  updatedAt?: true
  expiresAt?: true
}

export type ActionDraftMaxAggregateInputType = {
  id?: true
  userId?: true
  guildId?: true
  actionConfigId?: true
  rawParticipants?: true
  createdAt?: true
  updatedAt?: true
  expiresAt?: true
}

export type ActionDraftCountAggregateInputType = {
  id?: true
  userId?: true
  guildId?: true
  actionConfigId?: true
  rawParticipants?: true
  parsedNames?: true
  missingNames?: true
  createdAt?: true
  updatedAt?: true
  expiresAt?: true
  _all?: true
}

export type ActionDraftAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ActionDraft to aggregate.
   */
  where?: Prisma.ActionDraftWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActionDrafts to fetch.
   */
  orderBy?: Prisma.ActionDraftOrderByWithRelationInput | Prisma.ActionDraftOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ActionDraftWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActionDrafts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActionDrafts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ActionDrafts
  **/
  _count?: true | ActionDraftCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ActionDraftAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ActionDraftSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ActionDraftMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ActionDraftMaxAggregateInputType
}

export type GetActionDraftAggregateType<T extends ActionDraftAggregateArgs> = {
      [P in keyof T & keyof AggregateActionDraft]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateActionDraft[P]>
    : Prisma.GetScalarType<T[P], AggregateActionDraft[P]>
}




export type ActionDraftGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ActionDraftWhereInput
  orderBy?: Prisma.ActionDraftOrderByWithAggregationInput | Prisma.ActionDraftOrderByWithAggregationInput[]
  by: Prisma.ActionDraftScalarFieldEnum[] | Prisma.ActionDraftScalarFieldEnum
  having?: Prisma.ActionDraftScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ActionDraftCountAggregateInputType | true
  _avg?: ActionDraftAvgAggregateInputType
  _sum?: ActionDraftSumAggregateInputType
  _min?: ActionDraftMinAggregateInputType
  _max?: ActionDraftMaxAggregateInputType
}

export type ActionDraftGroupByOutputType = {
  id: string
  userId: string
  guildId: string
  actionConfigId: number
  rawParticipants: string
  parsedNames: string[]
  missingNames: string[]
  createdAt: Date
  updatedAt: Date
  expiresAt: Date
  _count: ActionDraftCountAggregateOutputType | null
  _avg: ActionDraftAvgAggregateOutputType | null
  _sum: ActionDraftSumAggregateOutputType | null
  _min: ActionDraftMinAggregateOutputType | null
  _max: ActionDraftMaxAggregateOutputType | null
}

type GetActionDraftGroupByPayload<T extends ActionDraftGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ActionDraftGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ActionDraftGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ActionDraftGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ActionDraftGroupByOutputType[P]>
      }
    >
  >



export type ActionDraftWhereInput = {
  AND?: Prisma.ActionDraftWhereInput | Prisma.ActionDraftWhereInput[]
  OR?: Prisma.ActionDraftWhereInput[]
  NOT?: Prisma.ActionDraftWhereInput | Prisma.ActionDraftWhereInput[]
  id?: Prisma.StringFilter<"ActionDraft"> | string
  userId?: Prisma.StringFilter<"ActionDraft"> | string
  guildId?: Prisma.StringFilter<"ActionDraft"> | string
  actionConfigId?: Prisma.IntFilter<"ActionDraft"> | number
  rawParticipants?: Prisma.StringFilter<"ActionDraft"> | string
  parsedNames?: Prisma.StringNullableListFilter<"ActionDraft">
  missingNames?: Prisma.StringNullableListFilter<"ActionDraft">
  createdAt?: Prisma.DateTimeFilter<"ActionDraft"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ActionDraft"> | Date | string
  expiresAt?: Prisma.DateTimeFilter<"ActionDraft"> | Date | string
  actionConfig?: Prisma.XOR<Prisma.ActionConfigScalarRelationFilter, Prisma.ActionConfigWhereInput>
  resolvedParticipants?: Prisma.ParticipantListRelationFilter
}

export type ActionDraftOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  actionConfigId?: Prisma.SortOrder
  rawParticipants?: Prisma.SortOrder
  parsedNames?: Prisma.SortOrder
  missingNames?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  actionConfig?: Prisma.ActionConfigOrderByWithRelationInput
  resolvedParticipants?: Prisma.ParticipantOrderByRelationAggregateInput
}

export type ActionDraftWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ActionDraftWhereInput | Prisma.ActionDraftWhereInput[]
  OR?: Prisma.ActionDraftWhereInput[]
  NOT?: Prisma.ActionDraftWhereInput | Prisma.ActionDraftWhereInput[]
  userId?: Prisma.StringFilter<"ActionDraft"> | string
  guildId?: Prisma.StringFilter<"ActionDraft"> | string
  actionConfigId?: Prisma.IntFilter<"ActionDraft"> | number
  rawParticipants?: Prisma.StringFilter<"ActionDraft"> | string
  parsedNames?: Prisma.StringNullableListFilter<"ActionDraft">
  missingNames?: Prisma.StringNullableListFilter<"ActionDraft">
  createdAt?: Prisma.DateTimeFilter<"ActionDraft"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ActionDraft"> | Date | string
  expiresAt?: Prisma.DateTimeFilter<"ActionDraft"> | Date | string
  actionConfig?: Prisma.XOR<Prisma.ActionConfigScalarRelationFilter, Prisma.ActionConfigWhereInput>
  resolvedParticipants?: Prisma.ParticipantListRelationFilter
}, "id">

export type ActionDraftOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  actionConfigId?: Prisma.SortOrder
  rawParticipants?: Prisma.SortOrder
  parsedNames?: Prisma.SortOrder
  missingNames?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  _count?: Prisma.ActionDraftCountOrderByAggregateInput
  _avg?: Prisma.ActionDraftAvgOrderByAggregateInput
  _max?: Prisma.ActionDraftMaxOrderByAggregateInput
  _min?: Prisma.ActionDraftMinOrderByAggregateInput
  _sum?: Prisma.ActionDraftSumOrderByAggregateInput
}

export type ActionDraftScalarWhereWithAggregatesInput = {
  AND?: Prisma.ActionDraftScalarWhereWithAggregatesInput | Prisma.ActionDraftScalarWhereWithAggregatesInput[]
  OR?: Prisma.ActionDraftScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ActionDraftScalarWhereWithAggregatesInput | Prisma.ActionDraftScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ActionDraft"> | string
  userId?: Prisma.StringWithAggregatesFilter<"ActionDraft"> | string
  guildId?: Prisma.StringWithAggregatesFilter<"ActionDraft"> | string
  actionConfigId?: Prisma.IntWithAggregatesFilter<"ActionDraft"> | number
  rawParticipants?: Prisma.StringWithAggregatesFilter<"ActionDraft"> | string
  parsedNames?: Prisma.StringNullableListFilter<"ActionDraft">
  missingNames?: Prisma.StringNullableListFilter<"ActionDraft">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ActionDraft"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ActionDraft"> | Date | string
  expiresAt?: Prisma.DateTimeWithAggregatesFilter<"ActionDraft"> | Date | string
}

export type ActionDraftCreateInput = {
  id?: string
  userId: string
  guildId: string
  rawParticipants: string
  parsedNames?: Prisma.ActionDraftCreateparsedNamesInput | string[]
  missingNames?: Prisma.ActionDraftCreatemissingNamesInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
  expiresAt: Date | string
  actionConfig: Prisma.ActionConfigCreateNestedOneWithoutActionDraftsInput
  resolvedParticipants?: Prisma.ParticipantCreateNestedManyWithoutDraftsInput
}

export type ActionDraftUncheckedCreateInput = {
  id?: string
  userId: string
  guildId: string
  actionConfigId: number
  rawParticipants: string
  parsedNames?: Prisma.ActionDraftCreateparsedNamesInput | string[]
  missingNames?: Prisma.ActionDraftCreatemissingNamesInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
  expiresAt: Date | string
  resolvedParticipants?: Prisma.ParticipantUncheckedCreateNestedManyWithoutDraftsInput
}

export type ActionDraftUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  rawParticipants?: Prisma.StringFieldUpdateOperationsInput | string
  parsedNames?: Prisma.ActionDraftUpdateparsedNamesInput | string[]
  missingNames?: Prisma.ActionDraftUpdatemissingNamesInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actionConfig?: Prisma.ActionConfigUpdateOneRequiredWithoutActionDraftsNestedInput
  resolvedParticipants?: Prisma.ParticipantUpdateManyWithoutDraftsNestedInput
}

export type ActionDraftUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  actionConfigId?: Prisma.IntFieldUpdateOperationsInput | number
  rawParticipants?: Prisma.StringFieldUpdateOperationsInput | string
  parsedNames?: Prisma.ActionDraftUpdateparsedNamesInput | string[]
  missingNames?: Prisma.ActionDraftUpdatemissingNamesInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedParticipants?: Prisma.ParticipantUncheckedUpdateManyWithoutDraftsNestedInput
}

export type ActionDraftCreateManyInput = {
  id?: string
  userId: string
  guildId: string
  actionConfigId: number
  rawParticipants: string
  parsedNames?: Prisma.ActionDraftCreateparsedNamesInput | string[]
  missingNames?: Prisma.ActionDraftCreatemissingNamesInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
  expiresAt: Date | string
}

export type ActionDraftUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  rawParticipants?: Prisma.StringFieldUpdateOperationsInput | string
  parsedNames?: Prisma.ActionDraftUpdateparsedNamesInput | string[]
  missingNames?: Prisma.ActionDraftUpdatemissingNamesInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActionDraftUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  actionConfigId?: Prisma.IntFieldUpdateOperationsInput | number
  rawParticipants?: Prisma.StringFieldUpdateOperationsInput | string
  parsedNames?: Prisma.ActionDraftUpdateparsedNamesInput | string[]
  missingNames?: Prisma.ActionDraftUpdatemissingNamesInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActionDraftListRelationFilter = {
  every?: Prisma.ActionDraftWhereInput
  some?: Prisma.ActionDraftWhereInput
  none?: Prisma.ActionDraftWhereInput
}

export type ActionDraftOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type ActionDraftCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  actionConfigId?: Prisma.SortOrder
  rawParticipants?: Prisma.SortOrder
  parsedNames?: Prisma.SortOrder
  missingNames?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
}

export type ActionDraftAvgOrderByAggregateInput = {
  actionConfigId?: Prisma.SortOrder
}

export type ActionDraftMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  actionConfigId?: Prisma.SortOrder
  rawParticipants?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
}

export type ActionDraftMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  actionConfigId?: Prisma.SortOrder
  rawParticipants?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
}

export type ActionDraftSumOrderByAggregateInput = {
  actionConfigId?: Prisma.SortOrder
}

export type ActionDraftCreateNestedManyWithoutActionConfigInput = {
  create?: Prisma.XOR<Prisma.ActionDraftCreateWithoutActionConfigInput, Prisma.ActionDraftUncheckedCreateWithoutActionConfigInput> | Prisma.ActionDraftCreateWithoutActionConfigInput[] | Prisma.ActionDraftUncheckedCreateWithoutActionConfigInput[]
  connectOrCreate?: Prisma.ActionDraftCreateOrConnectWithoutActionConfigInput | Prisma.ActionDraftCreateOrConnectWithoutActionConfigInput[]
  createMany?: Prisma.ActionDraftCreateManyActionConfigInputEnvelope
  connect?: Prisma.ActionDraftWhereUniqueInput | Prisma.ActionDraftWhereUniqueInput[]
}

export type ActionDraftUncheckedCreateNestedManyWithoutActionConfigInput = {
  create?: Prisma.XOR<Prisma.ActionDraftCreateWithoutActionConfigInput, Prisma.ActionDraftUncheckedCreateWithoutActionConfigInput> | Prisma.ActionDraftCreateWithoutActionConfigInput[] | Prisma.ActionDraftUncheckedCreateWithoutActionConfigInput[]
  connectOrCreate?: Prisma.ActionDraftCreateOrConnectWithoutActionConfigInput | Prisma.ActionDraftCreateOrConnectWithoutActionConfigInput[]
  createMany?: Prisma.ActionDraftCreateManyActionConfigInputEnvelope
  connect?: Prisma.ActionDraftWhereUniqueInput | Prisma.ActionDraftWhereUniqueInput[]
}

export type ActionDraftUpdateManyWithoutActionConfigNestedInput = {
  create?: Prisma.XOR<Prisma.ActionDraftCreateWithoutActionConfigInput, Prisma.ActionDraftUncheckedCreateWithoutActionConfigInput> | Prisma.ActionDraftCreateWithoutActionConfigInput[] | Prisma.ActionDraftUncheckedCreateWithoutActionConfigInput[]
  connectOrCreate?: Prisma.ActionDraftCreateOrConnectWithoutActionConfigInput | Prisma.ActionDraftCreateOrConnectWithoutActionConfigInput[]
  upsert?: Prisma.ActionDraftUpsertWithWhereUniqueWithoutActionConfigInput | Prisma.ActionDraftUpsertWithWhereUniqueWithoutActionConfigInput[]
  createMany?: Prisma.ActionDraftCreateManyActionConfigInputEnvelope
  set?: Prisma.ActionDraftWhereUniqueInput | Prisma.ActionDraftWhereUniqueInput[]
  disconnect?: Prisma.ActionDraftWhereUniqueInput | Prisma.ActionDraftWhereUniqueInput[]
  delete?: Prisma.ActionDraftWhereUniqueInput | Prisma.ActionDraftWhereUniqueInput[]
  connect?: Prisma.ActionDraftWhereUniqueInput | Prisma.ActionDraftWhereUniqueInput[]
  update?: Prisma.ActionDraftUpdateWithWhereUniqueWithoutActionConfigInput | Prisma.ActionDraftUpdateWithWhereUniqueWithoutActionConfigInput[]
  updateMany?: Prisma.ActionDraftUpdateManyWithWhereWithoutActionConfigInput | Prisma.ActionDraftUpdateManyWithWhereWithoutActionConfigInput[]
  deleteMany?: Prisma.ActionDraftScalarWhereInput | Prisma.ActionDraftScalarWhereInput[]
}

export type ActionDraftUncheckedUpdateManyWithoutActionConfigNestedInput = {
  create?: Prisma.XOR<Prisma.ActionDraftCreateWithoutActionConfigInput, Prisma.ActionDraftUncheckedCreateWithoutActionConfigInput> | Prisma.ActionDraftCreateWithoutActionConfigInput[] | Prisma.ActionDraftUncheckedCreateWithoutActionConfigInput[]
  connectOrCreate?: Prisma.ActionDraftCreateOrConnectWithoutActionConfigInput | Prisma.ActionDraftCreateOrConnectWithoutActionConfigInput[]
  upsert?: Prisma.ActionDraftUpsertWithWhereUniqueWithoutActionConfigInput | Prisma.ActionDraftUpsertWithWhereUniqueWithoutActionConfigInput[]
  createMany?: Prisma.ActionDraftCreateManyActionConfigInputEnvelope
  set?: Prisma.ActionDraftWhereUniqueInput | Prisma.ActionDraftWhereUniqueInput[]
  disconnect?: Prisma.ActionDraftWhereUniqueInput | Prisma.ActionDraftWhereUniqueInput[]
  delete?: Prisma.ActionDraftWhereUniqueInput | Prisma.ActionDraftWhereUniqueInput[]
  connect?: Prisma.ActionDraftWhereUniqueInput | Prisma.ActionDraftWhereUniqueInput[]
  update?: Prisma.ActionDraftUpdateWithWhereUniqueWithoutActionConfigInput | Prisma.ActionDraftUpdateWithWhereUniqueWithoutActionConfigInput[]
  updateMany?: Prisma.ActionDraftUpdateManyWithWhereWithoutActionConfigInput | Prisma.ActionDraftUpdateManyWithWhereWithoutActionConfigInput[]
  deleteMany?: Prisma.ActionDraftScalarWhereInput | Prisma.ActionDraftScalarWhereInput[]
}

export type ActionDraftCreateNestedManyWithoutResolvedParticipantsInput = {
  create?: Prisma.XOR<Prisma.ActionDraftCreateWithoutResolvedParticipantsInput, Prisma.ActionDraftUncheckedCreateWithoutResolvedParticipantsInput> | Prisma.ActionDraftCreateWithoutResolvedParticipantsInput[] | Prisma.ActionDraftUncheckedCreateWithoutResolvedParticipantsInput[]
  connectOrCreate?: Prisma.ActionDraftCreateOrConnectWithoutResolvedParticipantsInput | Prisma.ActionDraftCreateOrConnectWithoutResolvedParticipantsInput[]
  connect?: Prisma.ActionDraftWhereUniqueInput | Prisma.ActionDraftWhereUniqueInput[]
}

export type ActionDraftUncheckedCreateNestedManyWithoutResolvedParticipantsInput = {
  create?: Prisma.XOR<Prisma.ActionDraftCreateWithoutResolvedParticipantsInput, Prisma.ActionDraftUncheckedCreateWithoutResolvedParticipantsInput> | Prisma.ActionDraftCreateWithoutResolvedParticipantsInput[] | Prisma.ActionDraftUncheckedCreateWithoutResolvedParticipantsInput[]
  connectOrCreate?: Prisma.ActionDraftCreateOrConnectWithoutResolvedParticipantsInput | Prisma.ActionDraftCreateOrConnectWithoutResolvedParticipantsInput[]
  connect?: Prisma.ActionDraftWhereUniqueInput | Prisma.ActionDraftWhereUniqueInput[]
}

export type ActionDraftUpdateManyWithoutResolvedParticipantsNestedInput = {
  create?: Prisma.XOR<Prisma.ActionDraftCreateWithoutResolvedParticipantsInput, Prisma.ActionDraftUncheckedCreateWithoutResolvedParticipantsInput> | Prisma.ActionDraftCreateWithoutResolvedParticipantsInput[] | Prisma.ActionDraftUncheckedCreateWithoutResolvedParticipantsInput[]
  connectOrCreate?: Prisma.ActionDraftCreateOrConnectWithoutResolvedParticipantsInput | Prisma.ActionDraftCreateOrConnectWithoutResolvedParticipantsInput[]
  upsert?: Prisma.ActionDraftUpsertWithWhereUniqueWithoutResolvedParticipantsInput | Prisma.ActionDraftUpsertWithWhereUniqueWithoutResolvedParticipantsInput[]
  set?: Prisma.ActionDraftWhereUniqueInput | Prisma.ActionDraftWhereUniqueInput[]
  disconnect?: Prisma.ActionDraftWhereUniqueInput | Prisma.ActionDraftWhereUniqueInput[]
  delete?: Prisma.ActionDraftWhereUniqueInput | Prisma.ActionDraftWhereUniqueInput[]
  connect?: Prisma.ActionDraftWhereUniqueInput | Prisma.ActionDraftWhereUniqueInput[]
  update?: Prisma.ActionDraftUpdateWithWhereUniqueWithoutResolvedParticipantsInput | Prisma.ActionDraftUpdateWithWhereUniqueWithoutResolvedParticipantsInput[]
  updateMany?: Prisma.ActionDraftUpdateManyWithWhereWithoutResolvedParticipantsInput | Prisma.ActionDraftUpdateManyWithWhereWithoutResolvedParticipantsInput[]
  deleteMany?: Prisma.ActionDraftScalarWhereInput | Prisma.ActionDraftScalarWhereInput[]
}

export type ActionDraftUncheckedUpdateManyWithoutResolvedParticipantsNestedInput = {
  create?: Prisma.XOR<Prisma.ActionDraftCreateWithoutResolvedParticipantsInput, Prisma.ActionDraftUncheckedCreateWithoutResolvedParticipantsInput> | Prisma.ActionDraftCreateWithoutResolvedParticipantsInput[] | Prisma.ActionDraftUncheckedCreateWithoutResolvedParticipantsInput[]
  connectOrCreate?: Prisma.ActionDraftCreateOrConnectWithoutResolvedParticipantsInput | Prisma.ActionDraftCreateOrConnectWithoutResolvedParticipantsInput[]
  upsert?: Prisma.ActionDraftUpsertWithWhereUniqueWithoutResolvedParticipantsInput | Prisma.ActionDraftUpsertWithWhereUniqueWithoutResolvedParticipantsInput[]
  set?: Prisma.ActionDraftWhereUniqueInput | Prisma.ActionDraftWhereUniqueInput[]
  disconnect?: Prisma.ActionDraftWhereUniqueInput | Prisma.ActionDraftWhereUniqueInput[]
  delete?: Prisma.ActionDraftWhereUniqueInput | Prisma.ActionDraftWhereUniqueInput[]
  connect?: Prisma.ActionDraftWhereUniqueInput | Prisma.ActionDraftWhereUniqueInput[]
  update?: Prisma.ActionDraftUpdateWithWhereUniqueWithoutResolvedParticipantsInput | Prisma.ActionDraftUpdateWithWhereUniqueWithoutResolvedParticipantsInput[]
  updateMany?: Prisma.ActionDraftUpdateManyWithWhereWithoutResolvedParticipantsInput | Prisma.ActionDraftUpdateManyWithWhereWithoutResolvedParticipantsInput[]
  deleteMany?: Prisma.ActionDraftScalarWhereInput | Prisma.ActionDraftScalarWhereInput[]
}

export type ActionDraftCreateparsedNamesInput = {
  set: string[]
}

export type ActionDraftCreatemissingNamesInput = {
  set: string[]
}

export type ActionDraftUpdateparsedNamesInput = {
  set?: string[]
  push?: string | string[]
}

export type ActionDraftUpdatemissingNamesInput = {
  set?: string[]
  push?: string | string[]
}

export type ActionDraftCreateWithoutActionConfigInput = {
  id?: string
  userId: string
  guildId: string
  rawParticipants: string
  parsedNames?: Prisma.ActionDraftCreateparsedNamesInput | string[]
  missingNames?: Prisma.ActionDraftCreatemissingNamesInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
  expiresAt: Date | string
  resolvedParticipants?: Prisma.ParticipantCreateNestedManyWithoutDraftsInput
}

export type ActionDraftUncheckedCreateWithoutActionConfigInput = {
  id?: string
  userId: string
  guildId: string
  rawParticipants: string
  parsedNames?: Prisma.ActionDraftCreateparsedNamesInput | string[]
  missingNames?: Prisma.ActionDraftCreatemissingNamesInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
  expiresAt: Date | string
  resolvedParticipants?: Prisma.ParticipantUncheckedCreateNestedManyWithoutDraftsInput
}

export type ActionDraftCreateOrConnectWithoutActionConfigInput = {
  where: Prisma.ActionDraftWhereUniqueInput
  create: Prisma.XOR<Prisma.ActionDraftCreateWithoutActionConfigInput, Prisma.ActionDraftUncheckedCreateWithoutActionConfigInput>
}

export type ActionDraftCreateManyActionConfigInputEnvelope = {
  data: Prisma.ActionDraftCreateManyActionConfigInput | Prisma.ActionDraftCreateManyActionConfigInput[]
  skipDuplicates?: boolean
}

export type ActionDraftUpsertWithWhereUniqueWithoutActionConfigInput = {
  where: Prisma.ActionDraftWhereUniqueInput
  update: Prisma.XOR<Prisma.ActionDraftUpdateWithoutActionConfigInput, Prisma.ActionDraftUncheckedUpdateWithoutActionConfigInput>
  create: Prisma.XOR<Prisma.ActionDraftCreateWithoutActionConfigInput, Prisma.ActionDraftUncheckedCreateWithoutActionConfigInput>
}

export type ActionDraftUpdateWithWhereUniqueWithoutActionConfigInput = {
  where: Prisma.ActionDraftWhereUniqueInput
  data: Prisma.XOR<Prisma.ActionDraftUpdateWithoutActionConfigInput, Prisma.ActionDraftUncheckedUpdateWithoutActionConfigInput>
}

export type ActionDraftUpdateManyWithWhereWithoutActionConfigInput = {
  where: Prisma.ActionDraftScalarWhereInput
  data: Prisma.XOR<Prisma.ActionDraftUpdateManyMutationInput, Prisma.ActionDraftUncheckedUpdateManyWithoutActionConfigInput>
}

export type ActionDraftScalarWhereInput = {
  AND?: Prisma.ActionDraftScalarWhereInput | Prisma.ActionDraftScalarWhereInput[]
  OR?: Prisma.ActionDraftScalarWhereInput[]
  NOT?: Prisma.ActionDraftScalarWhereInput | Prisma.ActionDraftScalarWhereInput[]
  id?: Prisma.StringFilter<"ActionDraft"> | string
  userId?: Prisma.StringFilter<"ActionDraft"> | string
  guildId?: Prisma.StringFilter<"ActionDraft"> | string
  actionConfigId?: Prisma.IntFilter<"ActionDraft"> | number
  rawParticipants?: Prisma.StringFilter<"ActionDraft"> | string
  parsedNames?: Prisma.StringNullableListFilter<"ActionDraft">
  missingNames?: Prisma.StringNullableListFilter<"ActionDraft">
  createdAt?: Prisma.DateTimeFilter<"ActionDraft"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ActionDraft"> | Date | string
  expiresAt?: Prisma.DateTimeFilter<"ActionDraft"> | Date | string
}

export type ActionDraftCreateWithoutResolvedParticipantsInput = {
  id?: string
  userId: string
  guildId: string
  rawParticipants: string
  parsedNames?: Prisma.ActionDraftCreateparsedNamesInput | string[]
  missingNames?: Prisma.ActionDraftCreatemissingNamesInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
  expiresAt: Date | string
  actionConfig: Prisma.ActionConfigCreateNestedOneWithoutActionDraftsInput
}

export type ActionDraftUncheckedCreateWithoutResolvedParticipantsInput = {
  id?: string
  userId: string
  guildId: string
  actionConfigId: number
  rawParticipants: string
  parsedNames?: Prisma.ActionDraftCreateparsedNamesInput | string[]
  missingNames?: Prisma.ActionDraftCreatemissingNamesInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
  expiresAt: Date | string
}

export type ActionDraftCreateOrConnectWithoutResolvedParticipantsInput = {
  where: Prisma.ActionDraftWhereUniqueInput
  create: Prisma.XOR<Prisma.ActionDraftCreateWithoutResolvedParticipantsInput, Prisma.ActionDraftUncheckedCreateWithoutResolvedParticipantsInput>
}

export type ActionDraftUpsertWithWhereUniqueWithoutResolvedParticipantsInput = {
  where: Prisma.ActionDraftWhereUniqueInput
  update: Prisma.XOR<Prisma.ActionDraftUpdateWithoutResolvedParticipantsInput, Prisma.ActionDraftUncheckedUpdateWithoutResolvedParticipantsInput>
  create: Prisma.XOR<Prisma.ActionDraftCreateWithoutResolvedParticipantsInput, Prisma.ActionDraftUncheckedCreateWithoutResolvedParticipantsInput>
}

export type ActionDraftUpdateWithWhereUniqueWithoutResolvedParticipantsInput = {
  where: Prisma.ActionDraftWhereUniqueInput
  data: Prisma.XOR<Prisma.ActionDraftUpdateWithoutResolvedParticipantsInput, Prisma.ActionDraftUncheckedUpdateWithoutResolvedParticipantsInput>
}

export type ActionDraftUpdateManyWithWhereWithoutResolvedParticipantsInput = {
  where: Prisma.ActionDraftScalarWhereInput
  data: Prisma.XOR<Prisma.ActionDraftUpdateManyMutationInput, Prisma.ActionDraftUncheckedUpdateManyWithoutResolvedParticipantsInput>
}

export type ActionDraftCreateManyActionConfigInput = {
  id?: string
  userId: string
  guildId: string
  rawParticipants: string
  parsedNames?: Prisma.ActionDraftCreateparsedNamesInput | string[]
  missingNames?: Prisma.ActionDraftCreatemissingNamesInput | string[]
  createdAt?: Date | string
  updatedAt?: Date | string
  expiresAt: Date | string
}

export type ActionDraftUpdateWithoutActionConfigInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  rawParticipants?: Prisma.StringFieldUpdateOperationsInput | string
  parsedNames?: Prisma.ActionDraftUpdateparsedNamesInput | string[]
  missingNames?: Prisma.ActionDraftUpdatemissingNamesInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedParticipants?: Prisma.ParticipantUpdateManyWithoutDraftsNestedInput
}

export type ActionDraftUncheckedUpdateWithoutActionConfigInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  rawParticipants?: Prisma.StringFieldUpdateOperationsInput | string
  parsedNames?: Prisma.ActionDraftUpdateparsedNamesInput | string[]
  missingNames?: Prisma.ActionDraftUpdatemissingNamesInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resolvedParticipants?: Prisma.ParticipantUncheckedUpdateManyWithoutDraftsNestedInput
}

export type ActionDraftUncheckedUpdateManyWithoutActionConfigInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  rawParticipants?: Prisma.StringFieldUpdateOperationsInput | string
  parsedNames?: Prisma.ActionDraftUpdateparsedNamesInput | string[]
  missingNames?: Prisma.ActionDraftUpdatemissingNamesInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActionDraftUpdateWithoutResolvedParticipantsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  rawParticipants?: Prisma.StringFieldUpdateOperationsInput | string
  parsedNames?: Prisma.ActionDraftUpdateparsedNamesInput | string[]
  missingNames?: Prisma.ActionDraftUpdatemissingNamesInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actionConfig?: Prisma.ActionConfigUpdateOneRequiredWithoutActionDraftsNestedInput
}

export type ActionDraftUncheckedUpdateWithoutResolvedParticipantsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  actionConfigId?: Prisma.IntFieldUpdateOperationsInput | number
  rawParticipants?: Prisma.StringFieldUpdateOperationsInput | string
  parsedNames?: Prisma.ActionDraftUpdateparsedNamesInput | string[]
  missingNames?: Prisma.ActionDraftUpdatemissingNamesInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActionDraftUncheckedUpdateManyWithoutResolvedParticipantsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  actionConfigId?: Prisma.IntFieldUpdateOperationsInput | number
  rawParticipants?: Prisma.StringFieldUpdateOperationsInput | string
  parsedNames?: Prisma.ActionDraftUpdateparsedNamesInput | string[]
  missingNames?: Prisma.ActionDraftUpdatemissingNamesInput | string[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ActionDraftCountOutputType
 */

export type ActionDraftCountOutputType = {
  resolvedParticipants: number
}

export type ActionDraftCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  resolvedParticipants?: boolean | ActionDraftCountOutputTypeCountResolvedParticipantsArgs
}

/**
 * ActionDraftCountOutputType without action
 */
export type ActionDraftCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionDraftCountOutputType
   */
  select?: Prisma.ActionDraftCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ActionDraftCountOutputType without action
 */
export type ActionDraftCountOutputTypeCountResolvedParticipantsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ParticipantWhereInput
}


export type ActionDraftSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  guildId?: boolean
  actionConfigId?: boolean
  rawParticipants?: boolean
  parsedNames?: boolean
  missingNames?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  expiresAt?: boolean
  actionConfig?: boolean | Prisma.ActionConfigDefaultArgs<ExtArgs>
  resolvedParticipants?: boolean | Prisma.ActionDraft$resolvedParticipantsArgs<ExtArgs>
  _count?: boolean | Prisma.ActionDraftCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["actionDraft"]>

export type ActionDraftSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  guildId?: boolean
  actionConfigId?: boolean
  rawParticipants?: boolean
  parsedNames?: boolean
  missingNames?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  expiresAt?: boolean
  actionConfig?: boolean | Prisma.ActionConfigDefaultArgs<ExtArgs>
}, ExtArgs["result"]["actionDraft"]>

export type ActionDraftSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  guildId?: boolean
  actionConfigId?: boolean
  rawParticipants?: boolean
  parsedNames?: boolean
  missingNames?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  expiresAt?: boolean
  actionConfig?: boolean | Prisma.ActionConfigDefaultArgs<ExtArgs>
}, ExtArgs["result"]["actionDraft"]>

export type ActionDraftSelectScalar = {
  id?: boolean
  userId?: boolean
  guildId?: boolean
  actionConfigId?: boolean
  rawParticipants?: boolean
  parsedNames?: boolean
  missingNames?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  expiresAt?: boolean
}

export type ActionDraftOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "guildId" | "actionConfigId" | "rawParticipants" | "parsedNames" | "missingNames" | "createdAt" | "updatedAt" | "expiresAt", ExtArgs["result"]["actionDraft"]>
export type ActionDraftInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  actionConfig?: boolean | Prisma.ActionConfigDefaultArgs<ExtArgs>
  resolvedParticipants?: boolean | Prisma.ActionDraft$resolvedParticipantsArgs<ExtArgs>
  _count?: boolean | Prisma.ActionDraftCountOutputTypeDefaultArgs<ExtArgs>
}
export type ActionDraftIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  actionConfig?: boolean | Prisma.ActionConfigDefaultArgs<ExtArgs>
}
export type ActionDraftIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  actionConfig?: boolean | Prisma.ActionConfigDefaultArgs<ExtArgs>
}

export type $ActionDraftPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ActionDraft"
  objects: {
    actionConfig: Prisma.$ActionConfigPayload<ExtArgs>
    resolvedParticipants: Prisma.$ParticipantPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    guildId: string
    actionConfigId: number
    rawParticipants: string
    parsedNames: string[]
    missingNames: string[]
    createdAt: Date
    updatedAt: Date
    expiresAt: Date
  }, ExtArgs["result"]["actionDraft"]>
  composites: {}
}

export type ActionDraftGetPayload<S extends boolean | null | undefined | ActionDraftDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ActionDraftPayload, S>

export type ActionDraftCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ActionDraftFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ActionDraftCountAggregateInputType | true
  }

export interface ActionDraftDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ActionDraft'], meta: { name: 'ActionDraft' } }
  /**
   * Find zero or one ActionDraft that matches the filter.
   * @param {ActionDraftFindUniqueArgs} args - Arguments to find a ActionDraft
   * @example
   * // Get one ActionDraft
   * const actionDraft = await prisma.actionDraft.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ActionDraftFindUniqueArgs>(args: Prisma.SelectSubset<T, ActionDraftFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ActionDraftClient<runtime.Types.Result.GetResult<Prisma.$ActionDraftPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ActionDraft that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ActionDraftFindUniqueOrThrowArgs} args - Arguments to find a ActionDraft
   * @example
   * // Get one ActionDraft
   * const actionDraft = await prisma.actionDraft.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ActionDraftFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ActionDraftFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ActionDraftClient<runtime.Types.Result.GetResult<Prisma.$ActionDraftPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ActionDraft that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionDraftFindFirstArgs} args - Arguments to find a ActionDraft
   * @example
   * // Get one ActionDraft
   * const actionDraft = await prisma.actionDraft.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ActionDraftFindFirstArgs>(args?: Prisma.SelectSubset<T, ActionDraftFindFirstArgs<ExtArgs>>): Prisma.Prisma__ActionDraftClient<runtime.Types.Result.GetResult<Prisma.$ActionDraftPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ActionDraft that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionDraftFindFirstOrThrowArgs} args - Arguments to find a ActionDraft
   * @example
   * // Get one ActionDraft
   * const actionDraft = await prisma.actionDraft.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ActionDraftFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ActionDraftFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ActionDraftClient<runtime.Types.Result.GetResult<Prisma.$ActionDraftPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ActionDrafts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionDraftFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ActionDrafts
   * const actionDrafts = await prisma.actionDraft.findMany()
   * 
   * // Get first 10 ActionDrafts
   * const actionDrafts = await prisma.actionDraft.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const actionDraftWithIdOnly = await prisma.actionDraft.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ActionDraftFindManyArgs>(args?: Prisma.SelectSubset<T, ActionDraftFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActionDraftPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ActionDraft.
   * @param {ActionDraftCreateArgs} args - Arguments to create a ActionDraft.
   * @example
   * // Create one ActionDraft
   * const ActionDraft = await prisma.actionDraft.create({
   *   data: {
   *     // ... data to create a ActionDraft
   *   }
   * })
   * 
   */
  create<T extends ActionDraftCreateArgs>(args: Prisma.SelectSubset<T, ActionDraftCreateArgs<ExtArgs>>): Prisma.Prisma__ActionDraftClient<runtime.Types.Result.GetResult<Prisma.$ActionDraftPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ActionDrafts.
   * @param {ActionDraftCreateManyArgs} args - Arguments to create many ActionDrafts.
   * @example
   * // Create many ActionDrafts
   * const actionDraft = await prisma.actionDraft.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ActionDraftCreateManyArgs>(args?: Prisma.SelectSubset<T, ActionDraftCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ActionDrafts and returns the data saved in the database.
   * @param {ActionDraftCreateManyAndReturnArgs} args - Arguments to create many ActionDrafts.
   * @example
   * // Create many ActionDrafts
   * const actionDraft = await prisma.actionDraft.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ActionDrafts and only return the `id`
   * const actionDraftWithIdOnly = await prisma.actionDraft.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ActionDraftCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ActionDraftCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActionDraftPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ActionDraft.
   * @param {ActionDraftDeleteArgs} args - Arguments to delete one ActionDraft.
   * @example
   * // Delete one ActionDraft
   * const ActionDraft = await prisma.actionDraft.delete({
   *   where: {
   *     // ... filter to delete one ActionDraft
   *   }
   * })
   * 
   */
  delete<T extends ActionDraftDeleteArgs>(args: Prisma.SelectSubset<T, ActionDraftDeleteArgs<ExtArgs>>): Prisma.Prisma__ActionDraftClient<runtime.Types.Result.GetResult<Prisma.$ActionDraftPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ActionDraft.
   * @param {ActionDraftUpdateArgs} args - Arguments to update one ActionDraft.
   * @example
   * // Update one ActionDraft
   * const actionDraft = await prisma.actionDraft.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ActionDraftUpdateArgs>(args: Prisma.SelectSubset<T, ActionDraftUpdateArgs<ExtArgs>>): Prisma.Prisma__ActionDraftClient<runtime.Types.Result.GetResult<Prisma.$ActionDraftPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ActionDrafts.
   * @param {ActionDraftDeleteManyArgs} args - Arguments to filter ActionDrafts to delete.
   * @example
   * // Delete a few ActionDrafts
   * const { count } = await prisma.actionDraft.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ActionDraftDeleteManyArgs>(args?: Prisma.SelectSubset<T, ActionDraftDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ActionDrafts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionDraftUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ActionDrafts
   * const actionDraft = await prisma.actionDraft.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ActionDraftUpdateManyArgs>(args: Prisma.SelectSubset<T, ActionDraftUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ActionDrafts and returns the data updated in the database.
   * @param {ActionDraftUpdateManyAndReturnArgs} args - Arguments to update many ActionDrafts.
   * @example
   * // Update many ActionDrafts
   * const actionDraft = await prisma.actionDraft.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ActionDrafts and only return the `id`
   * const actionDraftWithIdOnly = await prisma.actionDraft.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ActionDraftUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ActionDraftUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActionDraftPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ActionDraft.
   * @param {ActionDraftUpsertArgs} args - Arguments to update or create a ActionDraft.
   * @example
   * // Update or create a ActionDraft
   * const actionDraft = await prisma.actionDraft.upsert({
   *   create: {
   *     // ... data to create a ActionDraft
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ActionDraft we want to update
   *   }
   * })
   */
  upsert<T extends ActionDraftUpsertArgs>(args: Prisma.SelectSubset<T, ActionDraftUpsertArgs<ExtArgs>>): Prisma.Prisma__ActionDraftClient<runtime.Types.Result.GetResult<Prisma.$ActionDraftPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ActionDrafts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionDraftCountArgs} args - Arguments to filter ActionDrafts to count.
   * @example
   * // Count the number of ActionDrafts
   * const count = await prisma.actionDraft.count({
   *   where: {
   *     // ... the filter for the ActionDrafts we want to count
   *   }
   * })
  **/
  count<T extends ActionDraftCountArgs>(
    args?: Prisma.Subset<T, ActionDraftCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ActionDraftCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ActionDraft.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionDraftAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ActionDraftAggregateArgs>(args: Prisma.Subset<T, ActionDraftAggregateArgs>): Prisma.PrismaPromise<GetActionDraftAggregateType<T>>

  /**
   * Group by ActionDraft.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActionDraftGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ActionDraftGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ActionDraftGroupByArgs['orderBy'] }
      : { orderBy?: ActionDraftGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ActionDraftGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetActionDraftGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ActionDraft model
 */
readonly fields: ActionDraftFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ActionDraft.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ActionDraftClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  actionConfig<T extends Prisma.ActionConfigDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ActionConfigDefaultArgs<ExtArgs>>): Prisma.Prisma__ActionConfigClient<runtime.Types.Result.GetResult<Prisma.$ActionConfigPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  resolvedParticipants<T extends Prisma.ActionDraft$resolvedParticipantsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ActionDraft$resolvedParticipantsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ParticipantPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ActionDraft model
 */
export interface ActionDraftFieldRefs {
  readonly id: Prisma.FieldRef<"ActionDraft", 'String'>
  readonly userId: Prisma.FieldRef<"ActionDraft", 'String'>
  readonly guildId: Prisma.FieldRef<"ActionDraft", 'String'>
  readonly actionConfigId: Prisma.FieldRef<"ActionDraft", 'Int'>
  readonly rawParticipants: Prisma.FieldRef<"ActionDraft", 'String'>
  readonly parsedNames: Prisma.FieldRef<"ActionDraft", 'String[]'>
  readonly missingNames: Prisma.FieldRef<"ActionDraft", 'String[]'>
  readonly createdAt: Prisma.FieldRef<"ActionDraft", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ActionDraft", 'DateTime'>
  readonly expiresAt: Prisma.FieldRef<"ActionDraft", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ActionDraft findUnique
 */
export type ActionDraftFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionDraft
   */
  select?: Prisma.ActionDraftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionDraft
   */
  omit?: Prisma.ActionDraftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionDraftInclude<ExtArgs> | null
  /**
   * Filter, which ActionDraft to fetch.
   */
  where: Prisma.ActionDraftWhereUniqueInput
}

/**
 * ActionDraft findUniqueOrThrow
 */
export type ActionDraftFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionDraft
   */
  select?: Prisma.ActionDraftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionDraft
   */
  omit?: Prisma.ActionDraftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionDraftInclude<ExtArgs> | null
  /**
   * Filter, which ActionDraft to fetch.
   */
  where: Prisma.ActionDraftWhereUniqueInput
}

/**
 * ActionDraft findFirst
 */
export type ActionDraftFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionDraft
   */
  select?: Prisma.ActionDraftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionDraft
   */
  omit?: Prisma.ActionDraftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionDraftInclude<ExtArgs> | null
  /**
   * Filter, which ActionDraft to fetch.
   */
  where?: Prisma.ActionDraftWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActionDrafts to fetch.
   */
  orderBy?: Prisma.ActionDraftOrderByWithRelationInput | Prisma.ActionDraftOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ActionDrafts.
   */
  cursor?: Prisma.ActionDraftWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActionDrafts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActionDrafts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ActionDrafts.
   */
  distinct?: Prisma.ActionDraftScalarFieldEnum | Prisma.ActionDraftScalarFieldEnum[]
}

/**
 * ActionDraft findFirstOrThrow
 */
export type ActionDraftFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionDraft
   */
  select?: Prisma.ActionDraftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionDraft
   */
  omit?: Prisma.ActionDraftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionDraftInclude<ExtArgs> | null
  /**
   * Filter, which ActionDraft to fetch.
   */
  where?: Prisma.ActionDraftWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActionDrafts to fetch.
   */
  orderBy?: Prisma.ActionDraftOrderByWithRelationInput | Prisma.ActionDraftOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ActionDrafts.
   */
  cursor?: Prisma.ActionDraftWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActionDrafts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActionDrafts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ActionDrafts.
   */
  distinct?: Prisma.ActionDraftScalarFieldEnum | Prisma.ActionDraftScalarFieldEnum[]
}

/**
 * ActionDraft findMany
 */
export type ActionDraftFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionDraft
   */
  select?: Prisma.ActionDraftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionDraft
   */
  omit?: Prisma.ActionDraftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionDraftInclude<ExtArgs> | null
  /**
   * Filter, which ActionDrafts to fetch.
   */
  where?: Prisma.ActionDraftWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActionDrafts to fetch.
   */
  orderBy?: Prisma.ActionDraftOrderByWithRelationInput | Prisma.ActionDraftOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ActionDrafts.
   */
  cursor?: Prisma.ActionDraftWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActionDrafts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActionDrafts.
   */
  skip?: number
  distinct?: Prisma.ActionDraftScalarFieldEnum | Prisma.ActionDraftScalarFieldEnum[]
}

/**
 * ActionDraft create
 */
export type ActionDraftCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionDraft
   */
  select?: Prisma.ActionDraftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionDraft
   */
  omit?: Prisma.ActionDraftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionDraftInclude<ExtArgs> | null
  /**
   * The data needed to create a ActionDraft.
   */
  data: Prisma.XOR<Prisma.ActionDraftCreateInput, Prisma.ActionDraftUncheckedCreateInput>
}

/**
 * ActionDraft createMany
 */
export type ActionDraftCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ActionDrafts.
   */
  data: Prisma.ActionDraftCreateManyInput | Prisma.ActionDraftCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ActionDraft createManyAndReturn
 */
export type ActionDraftCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionDraft
   */
  select?: Prisma.ActionDraftSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ActionDraft
   */
  omit?: Prisma.ActionDraftOmit<ExtArgs> | null
  /**
   * The data used to create many ActionDrafts.
   */
  data: Prisma.ActionDraftCreateManyInput | Prisma.ActionDraftCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionDraftIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ActionDraft update
 */
export type ActionDraftUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionDraft
   */
  select?: Prisma.ActionDraftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionDraft
   */
  omit?: Prisma.ActionDraftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionDraftInclude<ExtArgs> | null
  /**
   * The data needed to update a ActionDraft.
   */
  data: Prisma.XOR<Prisma.ActionDraftUpdateInput, Prisma.ActionDraftUncheckedUpdateInput>
  /**
   * Choose, which ActionDraft to update.
   */
  where: Prisma.ActionDraftWhereUniqueInput
}

/**
 * ActionDraft updateMany
 */
export type ActionDraftUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ActionDrafts.
   */
  data: Prisma.XOR<Prisma.ActionDraftUpdateManyMutationInput, Prisma.ActionDraftUncheckedUpdateManyInput>
  /**
   * Filter which ActionDrafts to update
   */
  where?: Prisma.ActionDraftWhereInput
  /**
   * Limit how many ActionDrafts to update.
   */
  limit?: number
}

/**
 * ActionDraft updateManyAndReturn
 */
export type ActionDraftUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionDraft
   */
  select?: Prisma.ActionDraftSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ActionDraft
   */
  omit?: Prisma.ActionDraftOmit<ExtArgs> | null
  /**
   * The data used to update ActionDrafts.
   */
  data: Prisma.XOR<Prisma.ActionDraftUpdateManyMutationInput, Prisma.ActionDraftUncheckedUpdateManyInput>
  /**
   * Filter which ActionDrafts to update
   */
  where?: Prisma.ActionDraftWhereInput
  /**
   * Limit how many ActionDrafts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionDraftIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ActionDraft upsert
 */
export type ActionDraftUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionDraft
   */
  select?: Prisma.ActionDraftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionDraft
   */
  omit?: Prisma.ActionDraftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionDraftInclude<ExtArgs> | null
  /**
   * The filter to search for the ActionDraft to update in case it exists.
   */
  where: Prisma.ActionDraftWhereUniqueInput
  /**
   * In case the ActionDraft found by the `where` argument doesn't exist, create a new ActionDraft with this data.
   */
  create: Prisma.XOR<Prisma.ActionDraftCreateInput, Prisma.ActionDraftUncheckedCreateInput>
  /**
   * In case the ActionDraft was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ActionDraftUpdateInput, Prisma.ActionDraftUncheckedUpdateInput>
}

/**
 * ActionDraft delete
 */
export type ActionDraftDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionDraft
   */
  select?: Prisma.ActionDraftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionDraft
   */
  omit?: Prisma.ActionDraftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionDraftInclude<ExtArgs> | null
  /**
   * Filter which ActionDraft to delete.
   */
  where: Prisma.ActionDraftWhereUniqueInput
}

/**
 * ActionDraft deleteMany
 */
export type ActionDraftDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ActionDrafts to delete
   */
  where?: Prisma.ActionDraftWhereInput
  /**
   * Limit how many ActionDrafts to delete.
   */
  limit?: number
}

/**
 * ActionDraft.resolvedParticipants
 */
export type ActionDraft$resolvedParticipantsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participant
   */
  select?: Prisma.ParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participant
   */
  omit?: Prisma.ParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantInclude<ExtArgs> | null
  where?: Prisma.ParticipantWhereInput
  orderBy?: Prisma.ParticipantOrderByWithRelationInput | Prisma.ParticipantOrderByWithRelationInput[]
  cursor?: Prisma.ParticipantWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ParticipantScalarFieldEnum | Prisma.ParticipantScalarFieldEnum[]
}

/**
 * ActionDraft without action
 */
export type ActionDraftDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActionDraft
   */
  select?: Prisma.ActionDraftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActionDraft
   */
  omit?: Prisma.ActionDraftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActionDraftInclude<ExtArgs> | null
}
