
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Punishment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Punishment
 * 
 */
export type PunishmentModel = runtime.Types.Result.DefaultSelection<Prisma.$PunishmentPayload>

export type AggregatePunishment = {
  _count: PunishmentCountAggregateOutputType | null
  _min: PunishmentMinAggregateOutputType | null
  _max: PunishmentMaxAggregateOutputType | null
}

export type PunishmentMinAggregateOutputType = {
  id: string | null
  memberId: string | null
  guildId: string | null
  type: $Enums.PunishmentType | null
  reason: string | null
  status: $Enums.PunishmentStatus | null
  expiresAt: Date | null
  appliedBy: string | null
  createdAt: Date | null
  canceledBy: string | null
  canceledAt: Date | null
}

export type PunishmentMaxAggregateOutputType = {
  id: string | null
  memberId: string | null
  guildId: string | null
  type: $Enums.PunishmentType | null
  reason: string | null
  status: $Enums.PunishmentStatus | null
  expiresAt: Date | null
  appliedBy: string | null
  createdAt: Date | null
  canceledBy: string | null
  canceledAt: Date | null
}

export type PunishmentCountAggregateOutputType = {
  id: number
  memberId: number
  guildId: number
  type: number
  reason: number
  status: number
  expiresAt: number
  appliedBy: number
  createdAt: number
  canceledBy: number
  canceledAt: number
  _all: number
}


export type PunishmentMinAggregateInputType = {
  id?: true
  memberId?: true
  guildId?: true
  type?: true
  reason?: true
  status?: true
  expiresAt?: true
  appliedBy?: true
  createdAt?: true
  canceledBy?: true
  canceledAt?: true
}

export type PunishmentMaxAggregateInputType = {
  id?: true
  memberId?: true
  guildId?: true
  type?: true
  reason?: true
  status?: true
  expiresAt?: true
  appliedBy?: true
  createdAt?: true
  canceledBy?: true
  canceledAt?: true
}

export type PunishmentCountAggregateInputType = {
  id?: true
  memberId?: true
  guildId?: true
  type?: true
  reason?: true
  status?: true
  expiresAt?: true
  appliedBy?: true
  createdAt?: true
  canceledBy?: true
  canceledAt?: true
  _all?: true
}

export type PunishmentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Punishment to aggregate.
   */
  where?: Prisma.PunishmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Punishments to fetch.
   */
  orderBy?: Prisma.PunishmentOrderByWithRelationInput | Prisma.PunishmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PunishmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Punishments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Punishments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Punishments
  **/
  _count?: true | PunishmentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PunishmentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PunishmentMaxAggregateInputType
}

export type GetPunishmentAggregateType<T extends PunishmentAggregateArgs> = {
      [P in keyof T & keyof AggregatePunishment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePunishment[P]>
    : Prisma.GetScalarType<T[P], AggregatePunishment[P]>
}




export type PunishmentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PunishmentWhereInput
  orderBy?: Prisma.PunishmentOrderByWithAggregationInput | Prisma.PunishmentOrderByWithAggregationInput[]
  by: Prisma.PunishmentScalarFieldEnum[] | Prisma.PunishmentScalarFieldEnum
  having?: Prisma.PunishmentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PunishmentCountAggregateInputType | true
  _min?: PunishmentMinAggregateInputType
  _max?: PunishmentMaxAggregateInputType
}

export type PunishmentGroupByOutputType = {
  id: string
  memberId: string
  guildId: string
  type: $Enums.PunishmentType
  reason: string
  status: $Enums.PunishmentStatus
  expiresAt: Date | null
  appliedBy: string
  createdAt: Date
  canceledBy: string | null
  canceledAt: Date | null
  _count: PunishmentCountAggregateOutputType | null
  _min: PunishmentMinAggregateOutputType | null
  _max: PunishmentMaxAggregateOutputType | null
}

type GetPunishmentGroupByPayload<T extends PunishmentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PunishmentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PunishmentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PunishmentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PunishmentGroupByOutputType[P]>
      }
    >
  >



export type PunishmentWhereInput = {
  AND?: Prisma.PunishmentWhereInput | Prisma.PunishmentWhereInput[]
  OR?: Prisma.PunishmentWhereInput[]
  NOT?: Prisma.PunishmentWhereInput | Prisma.PunishmentWhereInput[]
  id?: Prisma.StringFilter<"Punishment"> | string
  memberId?: Prisma.StringFilter<"Punishment"> | string
  guildId?: Prisma.StringFilter<"Punishment"> | string
  type?: Prisma.EnumPunishmentTypeFilter<"Punishment"> | $Enums.PunishmentType
  reason?: Prisma.StringFilter<"Punishment"> | string
  status?: Prisma.EnumPunishmentStatusFilter<"Punishment"> | $Enums.PunishmentStatus
  expiresAt?: Prisma.DateTimeNullableFilter<"Punishment"> | Date | string | null
  appliedBy?: Prisma.StringFilter<"Punishment"> | string
  createdAt?: Prisma.DateTimeFilter<"Punishment"> | Date | string
  canceledBy?: Prisma.StringNullableFilter<"Punishment"> | string | null
  canceledAt?: Prisma.DateTimeNullableFilter<"Punishment"> | Date | string | null
}

export type PunishmentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  status?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  appliedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  canceledBy?: Prisma.SortOrderInput | Prisma.SortOrder
  canceledAt?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type PunishmentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PunishmentWhereInput | Prisma.PunishmentWhereInput[]
  OR?: Prisma.PunishmentWhereInput[]
  NOT?: Prisma.PunishmentWhereInput | Prisma.PunishmentWhereInput[]
  memberId?: Prisma.StringFilter<"Punishment"> | string
  guildId?: Prisma.StringFilter<"Punishment"> | string
  type?: Prisma.EnumPunishmentTypeFilter<"Punishment"> | $Enums.PunishmentType
  reason?: Prisma.StringFilter<"Punishment"> | string
  status?: Prisma.EnumPunishmentStatusFilter<"Punishment"> | $Enums.PunishmentStatus
  expiresAt?: Prisma.DateTimeNullableFilter<"Punishment"> | Date | string | null
  appliedBy?: Prisma.StringFilter<"Punishment"> | string
  createdAt?: Prisma.DateTimeFilter<"Punishment"> | Date | string
  canceledBy?: Prisma.StringNullableFilter<"Punishment"> | string | null
  canceledAt?: Prisma.DateTimeNullableFilter<"Punishment"> | Date | string | null
}, "id">

export type PunishmentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  status?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  appliedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  canceledBy?: Prisma.SortOrderInput | Prisma.SortOrder
  canceledAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.PunishmentCountOrderByAggregateInput
  _max?: Prisma.PunishmentMaxOrderByAggregateInput
  _min?: Prisma.PunishmentMinOrderByAggregateInput
}

export type PunishmentScalarWhereWithAggregatesInput = {
  AND?: Prisma.PunishmentScalarWhereWithAggregatesInput | Prisma.PunishmentScalarWhereWithAggregatesInput[]
  OR?: Prisma.PunishmentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PunishmentScalarWhereWithAggregatesInput | Prisma.PunishmentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Punishment"> | string
  memberId?: Prisma.StringWithAggregatesFilter<"Punishment"> | string
  guildId?: Prisma.StringWithAggregatesFilter<"Punishment"> | string
  type?: Prisma.EnumPunishmentTypeWithAggregatesFilter<"Punishment"> | $Enums.PunishmentType
  reason?: Prisma.StringWithAggregatesFilter<"Punishment"> | string
  status?: Prisma.EnumPunishmentStatusWithAggregatesFilter<"Punishment"> | $Enums.PunishmentStatus
  expiresAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Punishment"> | Date | string | null
  appliedBy?: Prisma.StringWithAggregatesFilter<"Punishment"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Punishment"> | Date | string
  canceledBy?: Prisma.StringNullableWithAggregatesFilter<"Punishment"> | string | null
  canceledAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Punishment"> | Date | string | null
}

export type PunishmentCreateInput = {
  id?: string
  memberId: string
  guildId: string
  type: $Enums.PunishmentType
  reason: string
  status?: $Enums.PunishmentStatus
  expiresAt?: Date | string | null
  appliedBy: string
  createdAt?: Date | string
  canceledBy?: string | null
  canceledAt?: Date | string | null
}

export type PunishmentUncheckedCreateInput = {
  id?: string
  memberId: string
  guildId: string
  type: $Enums.PunishmentType
  reason: string
  status?: $Enums.PunishmentStatus
  expiresAt?: Date | string | null
  appliedBy: string
  createdAt?: Date | string
  canceledBy?: string | null
  canceledAt?: Date | string | null
}

export type PunishmentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumPunishmentTypeFieldUpdateOperationsInput | $Enums.PunishmentType
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPunishmentStatusFieldUpdateOperationsInput | $Enums.PunishmentStatus
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  appliedBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  canceledBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  canceledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PunishmentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumPunishmentTypeFieldUpdateOperationsInput | $Enums.PunishmentType
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPunishmentStatusFieldUpdateOperationsInput | $Enums.PunishmentStatus
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  appliedBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  canceledBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  canceledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PunishmentCreateManyInput = {
  id?: string
  memberId: string
  guildId: string
  type: $Enums.PunishmentType
  reason: string
  status?: $Enums.PunishmentStatus
  expiresAt?: Date | string | null
  appliedBy: string
  createdAt?: Date | string
  canceledBy?: string | null
  canceledAt?: Date | string | null
}

export type PunishmentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumPunishmentTypeFieldUpdateOperationsInput | $Enums.PunishmentType
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPunishmentStatusFieldUpdateOperationsInput | $Enums.PunishmentStatus
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  appliedBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  canceledBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  canceledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PunishmentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumPunishmentTypeFieldUpdateOperationsInput | $Enums.PunishmentType
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumPunishmentStatusFieldUpdateOperationsInput | $Enums.PunishmentStatus
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  appliedBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  canceledBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  canceledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type PunishmentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  status?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  appliedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  canceledBy?: Prisma.SortOrder
  canceledAt?: Prisma.SortOrder
}

export type PunishmentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  status?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  appliedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  canceledBy?: Prisma.SortOrder
  canceledAt?: Prisma.SortOrder
}

export type PunishmentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  status?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  appliedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  canceledBy?: Prisma.SortOrder
  canceledAt?: Prisma.SortOrder
}

export type EnumPunishmentTypeFieldUpdateOperationsInput = {
  set?: $Enums.PunishmentType
}

export type EnumPunishmentStatusFieldUpdateOperationsInput = {
  set?: $Enums.PunishmentStatus
}



export type PunishmentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  memberId?: boolean
  guildId?: boolean
  type?: boolean
  reason?: boolean
  status?: boolean
  expiresAt?: boolean
  appliedBy?: boolean
  createdAt?: boolean
  canceledBy?: boolean
  canceledAt?: boolean
}, ExtArgs["result"]["punishment"]>

export type PunishmentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  memberId?: boolean
  guildId?: boolean
  type?: boolean
  reason?: boolean
  status?: boolean
  expiresAt?: boolean
  appliedBy?: boolean
  createdAt?: boolean
  canceledBy?: boolean
  canceledAt?: boolean
}, ExtArgs["result"]["punishment"]>

export type PunishmentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  memberId?: boolean
  guildId?: boolean
  type?: boolean
  reason?: boolean
  status?: boolean
  expiresAt?: boolean
  appliedBy?: boolean
  createdAt?: boolean
  canceledBy?: boolean
  canceledAt?: boolean
}, ExtArgs["result"]["punishment"]>

export type PunishmentSelectScalar = {
  id?: boolean
  memberId?: boolean
  guildId?: boolean
  type?: boolean
  reason?: boolean
  status?: boolean
  expiresAt?: boolean
  appliedBy?: boolean
  createdAt?: boolean
  canceledBy?: boolean
  canceledAt?: boolean
}

export type PunishmentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "memberId" | "guildId" | "type" | "reason" | "status" | "expiresAt" | "appliedBy" | "createdAt" | "canceledBy" | "canceledAt", ExtArgs["result"]["punishment"]>

export type $PunishmentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Punishment"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    memberId: string
    guildId: string
    type: $Enums.PunishmentType
    reason: string
    status: $Enums.PunishmentStatus
    expiresAt: Date | null
    appliedBy: string
    createdAt: Date
    canceledBy: string | null
    canceledAt: Date | null
  }, ExtArgs["result"]["punishment"]>
  composites: {}
}

export type PunishmentGetPayload<S extends boolean | null | undefined | PunishmentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PunishmentPayload, S>

export type PunishmentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PunishmentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PunishmentCountAggregateInputType | true
  }

export interface PunishmentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Punishment'], meta: { name: 'Punishment' } }
  /**
   * Find zero or one Punishment that matches the filter.
   * @param {PunishmentFindUniqueArgs} args - Arguments to find a Punishment
   * @example
   * // Get one Punishment
   * const punishment = await prisma.punishment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PunishmentFindUniqueArgs>(args: Prisma.SelectSubset<T, PunishmentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PunishmentClient<runtime.Types.Result.GetResult<Prisma.$PunishmentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Punishment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PunishmentFindUniqueOrThrowArgs} args - Arguments to find a Punishment
   * @example
   * // Get one Punishment
   * const punishment = await prisma.punishment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PunishmentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PunishmentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PunishmentClient<runtime.Types.Result.GetResult<Prisma.$PunishmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Punishment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PunishmentFindFirstArgs} args - Arguments to find a Punishment
   * @example
   * // Get one Punishment
   * const punishment = await prisma.punishment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PunishmentFindFirstArgs>(args?: Prisma.SelectSubset<T, PunishmentFindFirstArgs<ExtArgs>>): Prisma.Prisma__PunishmentClient<runtime.Types.Result.GetResult<Prisma.$PunishmentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Punishment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PunishmentFindFirstOrThrowArgs} args - Arguments to find a Punishment
   * @example
   * // Get one Punishment
   * const punishment = await prisma.punishment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PunishmentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PunishmentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PunishmentClient<runtime.Types.Result.GetResult<Prisma.$PunishmentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Punishments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PunishmentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Punishments
   * const punishments = await prisma.punishment.findMany()
   * 
   * // Get first 10 Punishments
   * const punishments = await prisma.punishment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const punishmentWithIdOnly = await prisma.punishment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PunishmentFindManyArgs>(args?: Prisma.SelectSubset<T, PunishmentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PunishmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Punishment.
   * @param {PunishmentCreateArgs} args - Arguments to create a Punishment.
   * @example
   * // Create one Punishment
   * const Punishment = await prisma.punishment.create({
   *   data: {
   *     // ... data to create a Punishment
   *   }
   * })
   * 
   */
  create<T extends PunishmentCreateArgs>(args: Prisma.SelectSubset<T, PunishmentCreateArgs<ExtArgs>>): Prisma.Prisma__PunishmentClient<runtime.Types.Result.GetResult<Prisma.$PunishmentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Punishments.
   * @param {PunishmentCreateManyArgs} args - Arguments to create many Punishments.
   * @example
   * // Create many Punishments
   * const punishment = await prisma.punishment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PunishmentCreateManyArgs>(args?: Prisma.SelectSubset<T, PunishmentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Punishments and returns the data saved in the database.
   * @param {PunishmentCreateManyAndReturnArgs} args - Arguments to create many Punishments.
   * @example
   * // Create many Punishments
   * const punishment = await prisma.punishment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Punishments and only return the `id`
   * const punishmentWithIdOnly = await prisma.punishment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PunishmentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PunishmentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PunishmentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Punishment.
   * @param {PunishmentDeleteArgs} args - Arguments to delete one Punishment.
   * @example
   * // Delete one Punishment
   * const Punishment = await prisma.punishment.delete({
   *   where: {
   *     // ... filter to delete one Punishment
   *   }
   * })
   * 
   */
  delete<T extends PunishmentDeleteArgs>(args: Prisma.SelectSubset<T, PunishmentDeleteArgs<ExtArgs>>): Prisma.Prisma__PunishmentClient<runtime.Types.Result.GetResult<Prisma.$PunishmentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Punishment.
   * @param {PunishmentUpdateArgs} args - Arguments to update one Punishment.
   * @example
   * // Update one Punishment
   * const punishment = await prisma.punishment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PunishmentUpdateArgs>(args: Prisma.SelectSubset<T, PunishmentUpdateArgs<ExtArgs>>): Prisma.Prisma__PunishmentClient<runtime.Types.Result.GetResult<Prisma.$PunishmentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Punishments.
   * @param {PunishmentDeleteManyArgs} args - Arguments to filter Punishments to delete.
   * @example
   * // Delete a few Punishments
   * const { count } = await prisma.punishment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PunishmentDeleteManyArgs>(args?: Prisma.SelectSubset<T, PunishmentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Punishments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PunishmentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Punishments
   * const punishment = await prisma.punishment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PunishmentUpdateManyArgs>(args: Prisma.SelectSubset<T, PunishmentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Punishments and returns the data updated in the database.
   * @param {PunishmentUpdateManyAndReturnArgs} args - Arguments to update many Punishments.
   * @example
   * // Update many Punishments
   * const punishment = await prisma.punishment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Punishments and only return the `id`
   * const punishmentWithIdOnly = await prisma.punishment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PunishmentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PunishmentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PunishmentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Punishment.
   * @param {PunishmentUpsertArgs} args - Arguments to update or create a Punishment.
   * @example
   * // Update or create a Punishment
   * const punishment = await prisma.punishment.upsert({
   *   create: {
   *     // ... data to create a Punishment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Punishment we want to update
   *   }
   * })
   */
  upsert<T extends PunishmentUpsertArgs>(args: Prisma.SelectSubset<T, PunishmentUpsertArgs<ExtArgs>>): Prisma.Prisma__PunishmentClient<runtime.Types.Result.GetResult<Prisma.$PunishmentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Punishments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PunishmentCountArgs} args - Arguments to filter Punishments to count.
   * @example
   * // Count the number of Punishments
   * const count = await prisma.punishment.count({
   *   where: {
   *     // ... the filter for the Punishments we want to count
   *   }
   * })
  **/
  count<T extends PunishmentCountArgs>(
    args?: Prisma.Subset<T, PunishmentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PunishmentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Punishment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PunishmentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PunishmentAggregateArgs>(args: Prisma.Subset<T, PunishmentAggregateArgs>): Prisma.PrismaPromise<GetPunishmentAggregateType<T>>

  /**
   * Group by Punishment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PunishmentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PunishmentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PunishmentGroupByArgs['orderBy'] }
      : { orderBy?: PunishmentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PunishmentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPunishmentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Punishment model
 */
readonly fields: PunishmentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Punishment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PunishmentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Punishment model
 */
export interface PunishmentFieldRefs {
  readonly id: Prisma.FieldRef<"Punishment", 'String'>
  readonly memberId: Prisma.FieldRef<"Punishment", 'String'>
  readonly guildId: Prisma.FieldRef<"Punishment", 'String'>
  readonly type: Prisma.FieldRef<"Punishment", 'PunishmentType'>
  readonly reason: Prisma.FieldRef<"Punishment", 'String'>
  readonly status: Prisma.FieldRef<"Punishment", 'PunishmentStatus'>
  readonly expiresAt: Prisma.FieldRef<"Punishment", 'DateTime'>
  readonly appliedBy: Prisma.FieldRef<"Punishment", 'String'>
  readonly createdAt: Prisma.FieldRef<"Punishment", 'DateTime'>
  readonly canceledBy: Prisma.FieldRef<"Punishment", 'String'>
  readonly canceledAt: Prisma.FieldRef<"Punishment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Punishment findUnique
 */
export type PunishmentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishment
   */
  select?: Prisma.PunishmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Punishment
   */
  omit?: Prisma.PunishmentOmit<ExtArgs> | null
  /**
   * Filter, which Punishment to fetch.
   */
  where: Prisma.PunishmentWhereUniqueInput
}

/**
 * Punishment findUniqueOrThrow
 */
export type PunishmentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishment
   */
  select?: Prisma.PunishmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Punishment
   */
  omit?: Prisma.PunishmentOmit<ExtArgs> | null
  /**
   * Filter, which Punishment to fetch.
   */
  where: Prisma.PunishmentWhereUniqueInput
}

/**
 * Punishment findFirst
 */
export type PunishmentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishment
   */
  select?: Prisma.PunishmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Punishment
   */
  omit?: Prisma.PunishmentOmit<ExtArgs> | null
  /**
   * Filter, which Punishment to fetch.
   */
  where?: Prisma.PunishmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Punishments to fetch.
   */
  orderBy?: Prisma.PunishmentOrderByWithRelationInput | Prisma.PunishmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Punishments.
   */
  cursor?: Prisma.PunishmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Punishments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Punishments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Punishments.
   */
  distinct?: Prisma.PunishmentScalarFieldEnum | Prisma.PunishmentScalarFieldEnum[]
}

/**
 * Punishment findFirstOrThrow
 */
export type PunishmentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishment
   */
  select?: Prisma.PunishmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Punishment
   */
  omit?: Prisma.PunishmentOmit<ExtArgs> | null
  /**
   * Filter, which Punishment to fetch.
   */
  where?: Prisma.PunishmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Punishments to fetch.
   */
  orderBy?: Prisma.PunishmentOrderByWithRelationInput | Prisma.PunishmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Punishments.
   */
  cursor?: Prisma.PunishmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Punishments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Punishments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Punishments.
   */
  distinct?: Prisma.PunishmentScalarFieldEnum | Prisma.PunishmentScalarFieldEnum[]
}

/**
 * Punishment findMany
 */
export type PunishmentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishment
   */
  select?: Prisma.PunishmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Punishment
   */
  omit?: Prisma.PunishmentOmit<ExtArgs> | null
  /**
   * Filter, which Punishments to fetch.
   */
  where?: Prisma.PunishmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Punishments to fetch.
   */
  orderBy?: Prisma.PunishmentOrderByWithRelationInput | Prisma.PunishmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Punishments.
   */
  cursor?: Prisma.PunishmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Punishments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Punishments.
   */
  skip?: number
  distinct?: Prisma.PunishmentScalarFieldEnum | Prisma.PunishmentScalarFieldEnum[]
}

/**
 * Punishment create
 */
export type PunishmentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishment
   */
  select?: Prisma.PunishmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Punishment
   */
  omit?: Prisma.PunishmentOmit<ExtArgs> | null
  /**
   * The data needed to create a Punishment.
   */
  data: Prisma.XOR<Prisma.PunishmentCreateInput, Prisma.PunishmentUncheckedCreateInput>
}

/**
 * Punishment createMany
 */
export type PunishmentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Punishments.
   */
  data: Prisma.PunishmentCreateManyInput | Prisma.PunishmentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Punishment createManyAndReturn
 */
export type PunishmentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishment
   */
  select?: Prisma.PunishmentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Punishment
   */
  omit?: Prisma.PunishmentOmit<ExtArgs> | null
  /**
   * The data used to create many Punishments.
   */
  data: Prisma.PunishmentCreateManyInput | Prisma.PunishmentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Punishment update
 */
export type PunishmentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishment
   */
  select?: Prisma.PunishmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Punishment
   */
  omit?: Prisma.PunishmentOmit<ExtArgs> | null
  /**
   * The data needed to update a Punishment.
   */
  data: Prisma.XOR<Prisma.PunishmentUpdateInput, Prisma.PunishmentUncheckedUpdateInput>
  /**
   * Choose, which Punishment to update.
   */
  where: Prisma.PunishmentWhereUniqueInput
}

/**
 * Punishment updateMany
 */
export type PunishmentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Punishments.
   */
  data: Prisma.XOR<Prisma.PunishmentUpdateManyMutationInput, Prisma.PunishmentUncheckedUpdateManyInput>
  /**
   * Filter which Punishments to update
   */
  where?: Prisma.PunishmentWhereInput
  /**
   * Limit how many Punishments to update.
   */
  limit?: number
}

/**
 * Punishment updateManyAndReturn
 */
export type PunishmentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishment
   */
  select?: Prisma.PunishmentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Punishment
   */
  omit?: Prisma.PunishmentOmit<ExtArgs> | null
  /**
   * The data used to update Punishments.
   */
  data: Prisma.XOR<Prisma.PunishmentUpdateManyMutationInput, Prisma.PunishmentUncheckedUpdateManyInput>
  /**
   * Filter which Punishments to update
   */
  where?: Prisma.PunishmentWhereInput
  /**
   * Limit how many Punishments to update.
   */
  limit?: number
}

/**
 * Punishment upsert
 */
export type PunishmentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishment
   */
  select?: Prisma.PunishmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Punishment
   */
  omit?: Prisma.PunishmentOmit<ExtArgs> | null
  /**
   * The filter to search for the Punishment to update in case it exists.
   */
  where: Prisma.PunishmentWhereUniqueInput
  /**
   * In case the Punishment found by the `where` argument doesn't exist, create a new Punishment with this data.
   */
  create: Prisma.XOR<Prisma.PunishmentCreateInput, Prisma.PunishmentUncheckedCreateInput>
  /**
   * In case the Punishment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PunishmentUpdateInput, Prisma.PunishmentUncheckedUpdateInput>
}

/**
 * Punishment delete
 */
export type PunishmentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishment
   */
  select?: Prisma.PunishmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Punishment
   */
  omit?: Prisma.PunishmentOmit<ExtArgs> | null
  /**
   * Filter which Punishment to delete.
   */
  where: Prisma.PunishmentWhereUniqueInput
}

/**
 * Punishment deleteMany
 */
export type PunishmentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Punishments to delete
   */
  where?: Prisma.PunishmentWhereInput
  /**
   * Limit how many Punishments to delete.
   */
  limit?: number
}

/**
 * Punishment without action
 */
export type PunishmentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Punishment
   */
  select?: Prisma.PunishmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Punishment
   */
  omit?: Prisma.PunishmentOmit<ExtArgs> | null
}
