
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model ActionConfig
 * *
 *  * ======================================================
 *  * ACTION CONFIG (TIPOS DE AÇÃO)
 *  * ======================================================
 */
export type ActionConfig = Prisma.ActionConfigModel
/**
 * Model Action
 * *
 *  * ======================================================
 *  * ACTION (AÇÃO EM ANDAMENTO / FINALIZADA)
 *  * ======================================================
 */
export type Action = Prisma.ActionModel
/**
 * Model Participant
 * *
 *  * ======================================================
 *  * PARTICIPANT (PESSOA ÚNICA NO SISTEMA)
 *  * ======================================================
 */
export type Participant = Prisma.ParticipantModel
/**
 * Model ActionParticipant
 * *
 *  * ======================================================
 *  * ACTION PARTICIPANT (LIGAÇÃO)
 *  * ======================================================
 */
export type ActionParticipant = Prisma.ActionParticipantModel
/**
 * Model Punishment
 * 
 */
export type Punishment = Prisma.PunishmentModel
/**
 * Model ActionDraft
 * 
 */
export type ActionDraft = Prisma.ActionDraftModel
