
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const ActionStatus = {
  EM_ANDAMENTO: 'EM_ANDAMENTO',
  VITORIA: 'VITORIA',
  DERROTA: 'DERROTA',
  QTA: 'QTA'
} as const

export type ActionStatus = (typeof ActionStatus)[keyof typeof ActionStatus]


export const PunishmentType = {
  ADV1: 'ADV1',
  ADV2: 'ADV2',
  ADV3: 'ADV3',
  SUSPENSAO: 'SUSPENSAO'
} as const

export type PunishmentType = (typeof PunishmentType)[keyof typeof PunishmentType]


export const PunishmentStatus = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  CANCELED: 'CANCELED'
} as const

export type PunishmentStatus = (typeof PunishmentStatus)[keyof typeof PunishmentStatus]
