
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  ActionConfig: 'ActionConfig',
  Action: 'Action',
  Participant: 'Participant',
  ActionParticipant: 'ActionParticipant',
  Punishment: 'Punishment',
  ActionDraft: 'ActionDraft'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ActionConfigScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ActionConfigScalarFieldEnum = (typeof ActionConfigScalarFieldEnum)[keyof typeof ActionConfigScalarFieldEnum]


export const ActionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  status: 'status',
  responsible: 'responsible',
  actionConfigId: 'actionConfigId',
  createdAt: 'createdAt',
  finishedAt: 'finishedAt'
} as const

export type ActionScalarFieldEnum = (typeof ActionScalarFieldEnum)[keyof typeof ActionScalarFieldEnum]


export const ParticipantScalarFieldEnum = {
  id: 'id',
  idComplexo: 'idComplexo',
  name: 'name',
  unit: 'unit',
  createdAt: 'createdAt',
  actionDraftId: 'actionDraftId'
} as const

export type ParticipantScalarFieldEnum = (typeof ParticipantScalarFieldEnum)[keyof typeof ParticipantScalarFieldEnum]


export const ActionParticipantScalarFieldEnum = {
  id: 'id',
  actionId: 'actionId',
  participantId: 'participantId'
} as const

export type ActionParticipantScalarFieldEnum = (typeof ActionParticipantScalarFieldEnum)[keyof typeof ActionParticipantScalarFieldEnum]


export const PunishmentScalarFieldEnum = {
  id: 'id',
  memberId: 'memberId',
  guildId: 'guildId',
  type: 'type',
  reason: 'reason',
  status: 'status',
  expiresAt: 'expiresAt',
  appliedBy: 'appliedBy',
  createdAt: 'createdAt',
  canceledBy: 'canceledBy',
  canceledAt: 'canceledAt'
} as const

export type PunishmentScalarFieldEnum = (typeof PunishmentScalarFieldEnum)[keyof typeof PunishmentScalarFieldEnum]


export const ActionDraftScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  guildId: 'guildId',
  actionConfigId: 'actionConfigId',
  rawParticipants: 'rawParticipants',
  parsedNames: 'parsedNames',
  missingNames: 'missingNames',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  expiresAt: 'expiresAt'
} as const

export type ActionDraftScalarFieldEnum = (typeof ActionDraftScalarFieldEnum)[keyof typeof ActionDraftScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

